/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ScalarError } from "./scalarerror.js";

export type FourHundredAndFourData = {
  message: string;
  code: string;
};

export class FourHundredAndFour extends ScalarError {
  code: string;

  /** The original data that was passed to this error instance. */
  data$: FourHundredAndFourData;

  constructor(
    err: FourHundredAndFourData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;

    this.name = "FourHundredAndFour";
  }
}

/** @internal */
export const FourHundredAndFour$inboundSchema: z.ZodType<
  FourHundredAndFour,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  code: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new FourHundredAndFour(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type FourHundredAndFour$Outbound = {
  message: string;
  code: string;
};

/** @internal */
export const FourHundredAndFour$outboundSchema: z.ZodType<
  FourHundredAndFour$Outbound,
  z.ZodTypeDef,
  FourHundredAndFour
> = z.instanceof(FourHundredAndFour)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
    code: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FourHundredAndFour$ {
  /** @deprecated use `FourHundredAndFour$inboundSchema` instead. */
  export const inboundSchema = FourHundredAndFour$inboundSchema;
  /** @deprecated use `FourHundredAndFour$outboundSchema` instead. */
  export const outboundSchema = FourHundredAndFour$outboundSchema;
  /** @deprecated use `FourHundredAndFour$Outbound` instead. */
  export type Outbound = FourHundredAndFour$Outbound;
}
