/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type FourHundredData = {
  message: string;
  code: string;
};

export class FourHundred extends Error {
  code: string;

  /** The original data that was passed to this error instance. */
  data$: FourHundredData;

  constructor(err: FourHundredData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.code = err.code;

    this.name = "FourHundred";
  }
}

/** @internal */
export const FourHundred$inboundSchema: z.ZodType<
  FourHundred,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  code: z.string(),
})
  .transform((v) => {
    return new FourHundred(v);
  });

/** @internal */
export type FourHundred$Outbound = {
  message: string;
  code: string;
};

/** @internal */
export const FourHundred$outboundSchema: z.ZodType<
  FourHundred$Outbound,
  z.ZodTypeDef,
  FourHundred
> = z.instanceof(FourHundred)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
    code: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FourHundred$ {
  /** @deprecated use `FourHundred$inboundSchema` instead. */
  export const inboundSchema = FourHundred$inboundSchema;
  /** @deprecated use `FourHundred$outboundSchema` instead. */
  export const outboundSchema = FourHundred$outboundSchema;
  /** @deprecated use `FourHundred$Outbound` instead. */
  export type Outbound = FourHundred$Outbound;
}
