/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ScalarError } from "./scalarerror.js";

export type FourHundredAndOneData = {
  message: string;
  code: string;
};

export class FourHundredAndOne extends ScalarError {
  code: string;

  /** The original data that was passed to this error instance. */
  data$: FourHundredAndOneData;

  constructor(
    err: FourHundredAndOneData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;

    this.name = "FourHundredAndOne";
  }
}

/** @internal */
export const FourHundredAndOne$inboundSchema: z.ZodType<
  FourHundredAndOne,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  code: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new FourHundredAndOne(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type FourHundredAndOne$Outbound = {
  message: string;
  code: string;
};

/** @internal */
export const FourHundredAndOne$outboundSchema: z.ZodType<
  FourHundredAndOne$Outbound,
  z.ZodTypeDef,
  FourHundredAndOne
> = z.instanceof(FourHundredAndOne)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
    code: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FourHundredAndOne$ {
  /** @deprecated use `FourHundredAndOne$inboundSchema` instead. */
  export const inboundSchema = FourHundredAndOne$inboundSchema;
  /** @deprecated use `FourHundredAndOne$outboundSchema` instead. */
  export const outboundSchema = FourHundredAndOne$outboundSchema;
  /** @deprecated use `FourHundredAndOne$Outbound` instead. */
  export type Outbound = FourHundredAndOne$Outbound;
}
