/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ScalarError } from "./scalarerror.js";

export type FourHundredAndThreeData = {
  message: string;
  code: string;
};

export class FourHundredAndThree extends ScalarError {
  code: string;

  /** The original data that was passed to this error instance. */
  data$: FourHundredAndThreeData;

  constructor(
    err: FourHundredAndThreeData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;

    this.name = "FourHundredAndThree";
  }
}

/** @internal */
export const FourHundredAndThree$inboundSchema: z.ZodType<
  FourHundredAndThree,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  code: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new FourHundredAndThree(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type FourHundredAndThree$Outbound = {
  message: string;
  code: string;
};

/** @internal */
export const FourHundredAndThree$outboundSchema: z.ZodType<
  FourHundredAndThree$Outbound,
  z.ZodTypeDef,
  FourHundredAndThree
> = z.instanceof(FourHundredAndThree)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
    code: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FourHundredAndThree$ {
  /** @deprecated use `FourHundredAndThree$inboundSchema` instead. */
  export const inboundSchema = FourHundredAndThree$inboundSchema;
  /** @deprecated use `FourHundredAndThree$outboundSchema` instead. */
  export const outboundSchema = FourHundredAndThree$outboundSchema;
  /** @deprecated use `FourHundredAndThree$Outbound` instead. */
  export type Outbound = FourHundredAndThree$Outbound;
}
