/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiDocsDeletev1ApisNamespaceSlugVersionSemver } from "../../funcs/apiDocsDeletev1ApisNamespaceSlugVersionSemver.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations.Deletev1ApisNamespaceSlugVersionSemverRequest$inboundSchema,
};

export const tool$apiDocsDeletev1ApisNamespaceSlugVersionSemver: ToolDefinition<
  typeof args
> = {
  name: "API-docs-deletev1-apis-namespace-slug-version-semver",
  description: `Delete version

Delete a specific managed document version`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] =
      await apiDocsDeletev1ApisNamespaceSlugVersionSemver(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
