/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiDocsDeletev1ApisNamespaceSlug } from "../../funcs/apiDocsDeletev1ApisNamespaceSlug.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.Deletev1ApisNamespaceSlugRequest$inboundSchema,
};

export const tool$apiDocsDeletev1ApisNamespaceSlug: ToolDefinition<
  typeof args
> = {
  name: "API-docs-deletev1-apis-namespace-slug",
  description: `Delete an API

Delete a specific managed document and all of the related versions`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apiDocsDeletev1ApisNamespaceSlug(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
