/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiDocsPatchv1ApisNamespaceSlug } from "../../funcs/apiDocsPatchv1ApisNamespaceSlug.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.Patchv1ApisNamespaceSlugRequest$inboundSchema,
};

export const tool$apiDocsPatchv1ApisNamespaceSlug: ToolDefinition<typeof args> =
  {
    name: "API-docs-patchv1-apis-namespace-slug",
    description: `Update metadata

Update metadata for a specific managed document`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await apiDocsPatchv1ApisNamespaceSlug(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
