/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiDocsGetv1ApisNamespace } from "../../funcs/apiDocsGetv1ApisNamespace.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.Getv1ApisNamespaceRequest$inboundSchema,
};

export const tool$apiDocsGetv1ApisNamespace: ToolDefinition<typeof args> = {
  name: "API-docs-getv1-apis-namespace",
  description: `List all APIs

Get a list of all documents for the namespace`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apiDocsGetv1ApisNamespace(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
