/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiDocsGetv1ApisNamespaceSlugVersionSemver } from "../../funcs/apiDocsGetv1ApisNamespaceSlugVersionSemver.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.Getv1ApisNamespaceSlugVersionSemverRequest$inboundSchema,
};

export const tool$apiDocsGetv1ApisNamespaceSlugVersionSemver: ToolDefinition<
  typeof args
> = {
  name: "API-docs-getv1-apis-namespace-slug-version-semver",
  description: `Get API document

Get a specific managed document version stream`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apiDocsGetv1ApisNamespaceSlugVersionSemver(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
