/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiDocsPostv1ApisNamespaceSlugVersion } from "../../funcs/apiDocsPostv1ApisNamespaceSlugVersion.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.Postv1ApisNamespaceSlugVersionRequest$inboundSchema,
};

export const tool$apiDocsPostv1ApisNamespaceSlugVersion: ToolDefinition<
  typeof args
> = {
  name: "API-docs-postv1-apis-namespace-slug-version",
  description: `Create version

Create a new api document version`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apiDocsPostv1ApisNamespaceSlugVersion(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
