/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { guidesPostv1Guides } from "../../funcs/guidesPostv1Guides.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.Postv1GuidesRequestBody$inboundSchema,
};

export const tool$guidesPostv1Guides: ToolDefinition<typeof args> = {
  name: "guides-postv1-guides",
  description: `Create new project

Create a new guide project`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await guidesPostv1Guides(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
