/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { guidesPostv1GuidesSlugPublish } from "../../funcs/guidesPostv1GuidesSlugPublish.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.Postv1GuidesSlugPublishRequest$inboundSchema,
};

export const tool$guidesPostv1GuidesSlugPublish: ToolDefinition<typeof args> = {
  name: "guides-postv1-guides-slug-publish",
  description: `Publish project

Initiate a new publishing process`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await guidesPostv1GuidesSlugPublish(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
