/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { loginPortalsPatchv1LoginPortalsSlug } from "../../funcs/loginPortalsPatchv1LoginPortalsSlug.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.Patchv1LoginPortalsSlugRequest$inboundSchema,
};

export const tool$loginPortalsPatchv1LoginPortalsSlug: ToolDefinition<
  typeof args
> = {
  name: "login-portals-patchv1-login-portals-slug",
  description: `Update metadata

Update login portals metadata`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await loginPortalsPatchv1LoginPortalsSlug(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
