/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { loginPortalsGetv1LoginPortals } from "../../funcs/loginPortalsGetv1LoginPortals.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$loginPortalsGetv1LoginPortals: ToolDefinition = {
  name: "login-portals-getv1-login-portals",
  description: `List all portals

Get a list of all login portals for the team`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await loginPortalsGetv1LoginPortals(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
