/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { rulesDeletev1RulesetsNamespaceSlug } from "../../funcs/rulesDeletev1RulesetsNamespaceSlug.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.Deletev1RulesetsNamespaceSlugRequest$inboundSchema,
};

export const tool$rulesDeletev1RulesetsNamespaceSlug: ToolDefinition<
  typeof args
> = {
  name: "rules-deletev1-rulesets-namespace-slug",
  description: `Delete a rule

Delete a specific rule`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await rulesDeletev1RulesetsNamespaceSlug(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
