/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { rulesPostv1RulesetsNamespaceSlugAccessGroup } from "../../funcs/rulesPostv1RulesetsNamespaceSlugAccessGroup.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations.Postv1RulesetsNamespaceSlugAccessGroupRequest$inboundSchema,
};

export const tool$rulesPostv1RulesetsNamespaceSlugAccessGroup: ToolDefinition<
  typeof args
> = {
  name: "rules-postv1-rulesets-namespace-slug-access-group",
  description: `Add rule access group

Add an access group for the rule`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await rulesPostv1RulesetsNamespaceSlugAccessGroup(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
