/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { rulesPostv1RulesetsNamespace } from "../../funcs/rulesPostv1RulesetsNamespace.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.Postv1RulesetsNamespaceRequest$inboundSchema,
};

export const tool$rulesPostv1RulesetsNamespace: ToolDefinition<typeof args> = {
  name: "rules-postv1-rulesets-namespace",
  description: `Create a rule

Create a new rule for the namespace`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await rulesPostv1RulesetsNamespace(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
