/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { schemasPostv1SchemasNamespaceSlugAccessGroup } from "../../funcs/schemasPostv1SchemasNamespaceSlugAccessGroup.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations.Postv1SchemasNamespaceSlugAccessGroupRequest$inboundSchema,
};

export const tool$schemasPostv1SchemasNamespaceSlugAccessGroup: ToolDefinition<
  typeof args
> = {
  name: "schemas-postv1-schemas-namespace-slug-access-group",
  description: `Add shared component access group

Add access group to schema`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] =
      await schemasPostv1SchemasNamespaceSlugAccessGroup(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
