/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { schemasDeletev1SchemasNamespaceSlugVersionSemver } from "../../funcs/schemasDeletev1SchemasNamespaceSlugVersionSemver.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations.Deletev1SchemasNamespaceSlugVersionSemverRequest$inboundSchema,
};

export const tool$schemasDeletev1SchemasNamespaceSlugVersionSemver:
  ToolDefinition<typeof args> = {
    name: "schemas-deletev1-schemas-namespace-slug-version-semver",
    description: `Delete a shared component version

Delete a specific schema version`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await schemasDeletev1SchemasNamespaceSlugVersionSemver(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
