/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { schemasPatchv1SchemasNamespaceSlug } from "../../funcs/schemasPatchv1SchemasNamespaceSlug.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.Patchv1SchemasNamespaceSlugRequest$inboundSchema,
};

export const tool$schemasPatchv1SchemasNamespaceSlug: ToolDefinition<
  typeof args
> = {
  name: "schemas-patchv1-schemas-namespace-slug",
  description: `Update shared component metadata

Update schema metadata`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await schemasPatchv1SchemasNamespaceSlug(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
