/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { themesPostv1Themes } from "../../funcs/themesPostv1Themes.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.Postv1ThemesRequestBody$inboundSchema,
};

export const tool$themesPostv1Themes: ToolDefinition<typeof args> = {
  name: "themes-postv1-themes",
  description: `Create a theme

Create a new theme for the team`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await themesPostv1Themes(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
