/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { themesGetv1ThemesSlug } from "../../funcs/themesGetv1ThemesSlug.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.Getv1ThemesSlugRequest$inboundSchema,
};

export const tool$themesGetv1ThemesSlug: ToolDefinition<typeof args> = {
  name: "themes-getv1-themes-slug",
  description: `Get a theme

Get a the themes document`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await themesGetv1ThemesSlug(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
