/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { themesGetv1Themes } from "../../funcs/themesGetv1Themes.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$themesGetv1Themes: ToolDefinition = {
  name: "themes-getv1-themes",
  description: `List all themes

Get a list of all themes for the team`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await themesGetv1Themes(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
