/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { authenticationExchangePersonalToken } from "../funcs/authenticationExchangePersonalToken.js";
import { authenticationGetCurrentUser } from "../funcs/authenticationGetCurrentUser.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Authentication extends ClientSDK {
  /**
   * Exchange token
   *
   * @remarks
   * Exchange an API key for an access token.
   */
  async exchangePersonalToken(
    request: operations.ExchangePersonalTokenRequestBody,
    options?: RequestOptions,
  ): Promise<operations.ExchangePersonalTokenResponseBody> {
    return unwrapAsync(authenticationExchangePersonalToken(
      this,
      request,
      options,
    ));
  }

  /**
   * Get current user
   *
   * @remarks
   * Get the authenticated user, including their available teams and theme.
   */
  async getCurrentUser(
    options?: RequestOptions,
  ): Promise<components.User> {
    return unwrapAsync(authenticationGetCurrentUser(
      this,
      options,
    ));
  }
}
