/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { authenticationGetv1AuthMe } from "../funcs/authenticationGetv1AuthMe.js";
import { authenticationPostv1AuthExchange } from "../funcs/authenticationPostv1AuthExchange.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Authentication extends ClientSDK {
  /**
   * Exchange token
   *
   * @remarks
   * Exchange an API key for an access token.
   */
  async postv1AuthExchange(
    request: operations.Postv1AuthExchangeRequestBody,
    options?: RequestOptions,
  ): Promise<operations.Postv1AuthExchangeResponseBody> {
    return unwrapAsync(authenticationPostv1AuthExchange(
      this,
      request,
      options,
    ));
  }

  /**
   * Get current user
   *
   * @remarks
   * Get the authenticated user, including their available teams and theme.
   */
  async getv1AuthMe(
    options?: RequestOptions,
  ): Promise<components.User> {
    return unwrapAsync(authenticationGetv1AuthMe(
      this,
      options,
    ));
  }
}
