/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { loginPortalsCreateLoginPortal } from "../funcs/loginPortalsCreateLoginPortal.js";
import { loginPortalsDeleteLoginPortal } from "../funcs/loginPortalsDeleteLoginPortal.js";
import { loginPortalsGetLoginPortal } from "../funcs/loginPortalsGetLoginPortal.js";
import { loginPortalsListLoginPortals } from "../funcs/loginPortalsListLoginPortals.js";
import { loginPortalsUpdateLoginPortal } from "../funcs/loginPortalsUpdateLoginPortal.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class LoginPortals extends ClientSDK {
  /**
   * Get a login portal
   *
   * @remarks
   * Get a login portal by slug.
   */
  async getLoginPortal(
    request: operations.GetLoginPortalRequest,
    options?: RequestOptions,
  ): Promise<operations.GetLoginPortalResponse> {
    return unwrapAsync(loginPortalsGetLoginPortal(
      this,
      request,
      options,
    ));
  }

  /**
   * Update portal metadata
   *
   * @remarks
   * Update metadata for a login portal.
   */
  async updateLoginPortal(
    request: operations.UpdateLoginPortalRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateLoginPortalResponse> {
    return unwrapAsync(loginPortalsUpdateLoginPortal(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a login portal
   *
   * @remarks
   * Delete a login portal.
   */
  async deleteLoginPortal(
    request: operations.DeleteLoginPortalRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteLoginPortalResponse> {
    return unwrapAsync(loginPortalsDeleteLoginPortal(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a portal
   *
   * @remarks
   * Create a login portal for the current team.
   */
  async createLoginPortal(
    request: operations.CreateLoginPortalRequestBody,
    options?: RequestOptions,
  ): Promise<operations.CreateLoginPortalResponse> {
    return unwrapAsync(loginPortalsCreateLoginPortal(
      this,
      request,
      options,
    ));
  }

  /**
   * List all portals
   *
   * @remarks
   * List all login portals for the current team.
   */
  async listLoginPortals(
    options?: RequestOptions,
  ): Promise<operations.ListLoginPortalsResponse> {
    return unwrapAsync(loginPortalsListLoginPortals(
      this,
      options,
    ));
  }
}
