/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { namespacesListNamespaces } from "../funcs/namespacesListNamespaces.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";

export class Namespaces extends ClientSDK {
  /**
   * List namespaces
   *
   * @remarks
   * Get all namespaces for the current team
   */
  async listNamespaces(
    options?: RequestOptions,
  ): Promise<Array<string>> {
    return unwrapAsync(namespacesListNamespaces(
      this,
      options,
    ));
  }
}
