/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { registryAddApiDocumentAccessGroup } from "../funcs/registryAddApiDocumentAccessGroup.js";
import { registryCreateApiDocument } from "../funcs/registryCreateApiDocument.js";
import { registryCreateApiDocumentVersion } from "../funcs/registryCreateApiDocumentVersion.js";
import { registryDeleteApiDocument } from "../funcs/registryDeleteApiDocument.js";
import { registryDeleteApiDocumentVersion } from "../funcs/registryDeleteApiDocumentVersion.js";
import { registryGetApiDocumentVersion } from "../funcs/registryGetApiDocumentVersion.js";
import { registryGetApiDocumentVersionMetadata } from "../funcs/registryGetApiDocumentVersionMetadata.js";
import { registryListAllApiDocuments } from "../funcs/registryListAllApiDocuments.js";
import { registryListApiDocuments } from "../funcs/registryListApiDocuments.js";
import { registryRemoveApiDocumentAccessGroup } from "../funcs/registryRemoveApiDocumentAccessGroup.js";
import { registryUpdateApiDocument } from "../funcs/registryUpdateApiDocument.js";
import { registryUpdateApiDocumentVersion } from "../funcs/registryUpdateApiDocumentVersion.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Registry extends ClientSDK {
  /**
   * List all API Documents
   *
   * @remarks
   * List all API documents across every namespace the caller can access.
   */
  async listAllApiDocuments(
    options?: RequestOptions,
  ): Promise<Array<components.ApiDocument>> {
    return unwrapAsync(registryListAllApiDocuments(
      this,
      options,
    ));
  }

  /**
   * List API Documents in a namespace
   *
   * @remarks
   * List API documents in a namespace.
   */
  async listApiDocuments(
    request: operations.ListApiDocumentsRequest,
    options?: RequestOptions,
  ): Promise<Array<components.ApiDocument>> {
    return unwrapAsync(registryListApiDocuments(
      this,
      request,
      options,
    ));
  }

  /**
   * Create API Document
   *
   * @remarks
   * Create an API document.
   */
  async createApiDocument(
    request: operations.CreateApiDocumentRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateApiDocumentResponseBody> {
    return unwrapAsync(registryCreateApiDocument(
      this,
      request,
      options,
    ));
  }

  /**
   * Update API Document metadata
   *
   * @remarks
   * Update metadata for an API document.
   */
  async updateApiDocument(
    request: operations.UpdateApiDocumentRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(registryUpdateApiDocument(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete API Document
   *
   * @remarks
   * Delete an API document and all versions.
   */
  async deleteApiDocument(
    request: operations.DeleteApiDocumentRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(registryDeleteApiDocument(
      this,
      request,
      options,
    ));
  }

  /**
   * Get API Document
   *
   * @remarks
   * Get a specific API document version.
   */
  async getApiDocumentVersion(
    request: operations.GetApiDocumentVersionRequest,
    options?: RequestOptions,
  ): Promise<string> {
    return unwrapAsync(registryGetApiDocumentVersion(
      this,
      request,
      options,
    ));
  }

  /**
   * Update API Document version
   *
   * @remarks
   * Update the registry file content for an API document version.
   */
  async updateApiDocumentVersion(
    request: operations.UpdateApiDocumentVersionRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateApiDocumentVersionResponseBody> {
    return unwrapAsync(registryUpdateApiDocumentVersion(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete API Document version
   *
   * @remarks
   * Delete a specific API document version.
   */
  async deleteApiDocumentVersion(
    request: operations.DeleteApiDocumentVersionRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(registryDeleteApiDocumentVersion(
      this,
      request,
      options,
    ));
  }

  /**
   * Get API Document version metadata
   *
   * @remarks
   * Get metadata (uid, content shas, version sha, tags) for a specific API document version.
   */
  async getApiDocumentVersionMetadata(
    request: operations.GetApiDocumentVersionMetadataRequest,
    options?: RequestOptions,
  ): Promise<components.ManagedDocVersion> {
    return unwrapAsync(registryGetApiDocumentVersionMetadata(
      this,
      request,
      options,
    ));
  }

  /**
   * Create API Document version
   *
   * @remarks
   * Create a new API document version.
   */
  async createApiDocumentVersion(
    request: operations.CreateApiDocumentVersionRequest,
    options?: RequestOptions,
  ): Promise<components.ManagedDocVersion> {
    return unwrapAsync(registryCreateApiDocumentVersion(
      this,
      request,
      options,
    ));
  }

  /**
   * Add access group
   *
   * @remarks
   * Add an access group to an API document.
   */
  async addApiDocumentAccessGroup(
    request: operations.AddApiDocumentAccessGroupRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(registryAddApiDocumentAccessGroup(
      this,
      request,
      options,
    ));
  }

  /**
   * Remove access group
   *
   * @remarks
   * Remove an access group from an API document.
   */
  async removeApiDocumentAccessGroup(
    request: operations.RemoveApiDocumentAccessGroupRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(registryRemoveApiDocumentAccessGroup(
      this,
      request,
      options,
    ));
  }
}
