/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { rulesAddRulesetAccessGroup } from "../funcs/rulesAddRulesetAccessGroup.js";
import { rulesCreateRuleset } from "../funcs/rulesCreateRuleset.js";
import { rulesDeleteRuleset } from "../funcs/rulesDeleteRuleset.js";
import { rulesGetRulesetDocument } from "../funcs/rulesGetRulesetDocument.js";
import { rulesListRulesets } from "../funcs/rulesListRulesets.js";
import { rulesRemoveRulesetAccessGroup } from "../funcs/rulesRemoveRulesetAccessGroup.js";
import { rulesUpdateRuleset } from "../funcs/rulesUpdateRuleset.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Rules extends ClientSDK {
  /**
   * List all rules
   *
   * @remarks
   * List all rulesets in a namespace.
   */
  async listRulesets(
    request: operations.ListRulesetsRequest,
    options?: RequestOptions,
  ): Promise<operations.ListRulesetsResponse> {
    return unwrapAsync(rulesListRulesets(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a rule
   *
   * @remarks
   * Create a rule in a namespace.
   */
  async createRuleset(
    request: operations.CreateRulesetRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateRulesetResponse> {
    return unwrapAsync(rulesCreateRuleset(
      this,
      request,
      options,
    ));
  }

  /**
   * Update rule metadata
   *
   * @remarks
   * Update rule metadata by slug.
   */
  async updateRuleset(
    request: operations.UpdateRulesetRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateRulesetResponse> {
    return unwrapAsync(rulesUpdateRuleset(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a rule
   *
   * @remarks
   * Delete a rule by slug.
   */
  async deleteRuleset(
    request: operations.DeleteRulesetRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteRulesetResponse> {
    return unwrapAsync(rulesDeleteRuleset(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a rule
   *
   * @remarks
   * Get a rule document by slug.
   */
  async getRulesetDocument(
    request: operations.GetRulesetDocumentRequest,
    options?: RequestOptions,
  ): Promise<operations.GetRulesetDocumentResponse> {
    return unwrapAsync(rulesGetRulesetDocument(
      this,
      request,
      options,
    ));
  }

  /**
   * Add rule access group
   *
   * @remarks
   * Grant an access group to a rule.
   */
  async addRulesetAccessGroup(
    request: operations.AddRulesetAccessGroupRequest,
    options?: RequestOptions,
  ): Promise<operations.AddRulesetAccessGroupResponse> {
    return unwrapAsync(rulesAddRulesetAccessGroup(
      this,
      request,
      options,
    ));
  }

  /**
   * Remove rule access group
   *
   * @remarks
   * Remove an access group from a rule.
   */
  async removeRulesetAccessGroup(
    request: operations.RemoveRulesetAccessGroupRequest,
    options?: RequestOptions,
  ): Promise<operations.RemoveRulesetAccessGroupResponse> {
    return unwrapAsync(rulesRemoveRulesetAccessGroup(
      this,
      request,
      options,
    ));
  }
}
