/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { rulesDeletev1RulesetsNamespaceSlug } from "../funcs/rulesDeletev1RulesetsNamespaceSlug.js";
import { rulesDeletev1RulesetsNamespaceSlugAccessGroup } from "../funcs/rulesDeletev1RulesetsNamespaceSlugAccessGroup.js";
import { rulesGetv1RulesetsNamespace } from "../funcs/rulesGetv1RulesetsNamespace.js";
import { rulesGetv1RulesetsNamespaceSlug } from "../funcs/rulesGetv1RulesetsNamespaceSlug.js";
import { rulesPatchv1RulesetsNamespaceSlug } from "../funcs/rulesPatchv1RulesetsNamespaceSlug.js";
import { rulesPostv1RulesetsNamespace } from "../funcs/rulesPostv1RulesetsNamespace.js";
import { rulesPostv1RulesetsNamespaceSlugAccessGroup } from "../funcs/rulesPostv1RulesetsNamespaceSlugAccessGroup.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Rules extends ClientSDK {
  /**
   * List all rules
   *
   * @remarks
   * List all rulesets in a namespace.
   */
  async getv1RulesetsNamespace(
    request: operations.Getv1RulesetsNamespaceRequest,
    options?: RequestOptions,
  ): Promise<Array<components.Rule>> {
    return unwrapAsync(rulesGetv1RulesetsNamespace(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a rule
   *
   * @remarks
   * Create a rule in a namespace.
   */
  async postv1RulesetsNamespace(
    request: operations.Postv1RulesetsNamespaceRequest,
    options?: RequestOptions,
  ): Promise<components.Uid> {
    return unwrapAsync(rulesPostv1RulesetsNamespace(
      this,
      request,
      options,
    ));
  }

  /**
   * Update rule metadata
   *
   * @remarks
   * Update rule metadata by slug.
   */
  async patchv1RulesetsNamespaceSlug(
    request: operations.Patchv1RulesetsNamespaceSlugRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(rulesPatchv1RulesetsNamespaceSlug(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a rule
   *
   * @remarks
   * Delete a rule by slug.
   */
  async deletev1RulesetsNamespaceSlug(
    request: operations.Deletev1RulesetsNamespaceSlugRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(rulesDeletev1RulesetsNamespaceSlug(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a rule
   *
   * @remarks
   * Get a rule document by slug.
   */
  async getv1RulesetsNamespaceSlug(
    request: operations.Getv1RulesetsNamespaceSlugRequest,
    options?: RequestOptions,
  ): Promise<string> {
    return unwrapAsync(rulesGetv1RulesetsNamespaceSlug(
      this,
      request,
      options,
    ));
  }

  /**
   * Add rule access group
   *
   * @remarks
   * Grant an access group to a rule.
   */
  async postv1RulesetsNamespaceSlugAccessGroup(
    request: operations.Postv1RulesetsNamespaceSlugAccessGroupRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(rulesPostv1RulesetsNamespaceSlugAccessGroup(
      this,
      request,
      options,
    ));
  }

  /**
   * Remove rule access group
   *
   * @remarks
   * Remove an access group from a rule.
   */
  async deletev1RulesetsNamespaceSlugAccessGroup(
    request: operations.Deletev1RulesetsNamespaceSlugAccessGroupRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(rulesDeletev1RulesetsNamespaceSlugAccessGroup(
      this,
      request,
      options,
    ));
  }
}
