/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { scalarDocsCreateGuide } from "../funcs/scalarDocsCreateGuide.js";
import { scalarDocsListGuides } from "../funcs/scalarDocsListGuides.js";
import { scalarDocsPublishGuide } from "../funcs/scalarDocsPublishGuide.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ScalarDocs extends ClientSDK {
  /**
   * List all projects
   *
   * @remarks
   * List all guide projects.
   */
  async listGuides(
    options?: RequestOptions,
  ): Promise<operations.ListGuidesResponse> {
    return unwrapAsync(scalarDocsListGuides(
      this,
      options,
    ));
  }

  /**
   * Create a project
   *
   * @remarks
   * Create a guide project.
   */
  async createGuide(
    request: operations.CreateGuideRequestBody,
    options?: RequestOptions,
  ): Promise<operations.CreateGuideResponse> {
    return unwrapAsync(scalarDocsCreateGuide(
      this,
      request,
      options,
    ));
  }

  /**
   * Publish a project
   *
   * @remarks
   * Start a new publish process.
   */
  async publishGuide(
    request: operations.PublishGuideRequest,
    options?: RequestOptions,
  ): Promise<operations.PublishGuideResponse> {
    return unwrapAsync(scalarDocsPublishGuide(
      this,
      request,
      options,
    ));
  }
}
