/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { schemasAddSchemaAccessGroup } from "../funcs/schemasAddSchemaAccessGroup.js";
import { schemasCreateSchema } from "../funcs/schemasCreateSchema.js";
import { schemasCreateSchemaVersion } from "../funcs/schemasCreateSchemaVersion.js";
import { schemasDeleteSchema } from "../funcs/schemasDeleteSchema.js";
import { schemasDeleteSchemaVersion } from "../funcs/schemasDeleteSchemaVersion.js";
import { schemasGetSchemaVersion } from "../funcs/schemasGetSchemaVersion.js";
import { schemasListSchemas } from "../funcs/schemasListSchemas.js";
import { schemasRemoveSchemaAccessGroup } from "../funcs/schemasRemoveSchemaAccessGroup.js";
import { schemasUpdateSchema } from "../funcs/schemasUpdateSchema.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Schemas extends ClientSDK {
  /**
   * List all shared components
   *
   * @remarks
   * List schemas in a namespace.
   */
  async listSchemas(
    request: operations.ListSchemasRequest,
    options?: RequestOptions,
  ): Promise<operations.ListSchemasResponse> {
    return unwrapAsync(schemasListSchemas(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a shared component
   *
   * @remarks
   * Create a schema in a namespace.
   */
  async createSchema(
    request: operations.CreateSchemaRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateSchemaResponse> {
    return unwrapAsync(schemasCreateSchema(
      this,
      request,
      options,
    ));
  }

  /**
   * Update shared component metadata
   *
   * @remarks
   * Update schema metadata.
   */
  async updateSchema(
    request: operations.UpdateSchemaRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateSchemaResponse> {
    return unwrapAsync(schemasUpdateSchema(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a shared component
   *
   * @remarks
   * Delete a schema and all related versions.
   */
  async deleteSchema(
    request: operations.DeleteSchemaRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteSchemaResponse> {
    return unwrapAsync(schemasDeleteSchema(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a shared component document
   *
   * @remarks
   * Get a specific schema version document.
   */
  async getSchemaVersion(
    request: operations.GetSchemaVersionRequest,
    options?: RequestOptions,
  ): Promise<operations.GetSchemaVersionResponse> {
    return unwrapAsync(schemasGetSchemaVersion(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a shared component version
   *
   * @remarks
   * Delete a schema version.
   */
  async deleteSchemaVersion(
    request: operations.DeleteSchemaVersionRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteSchemaVersionResponse> {
    return unwrapAsync(schemasDeleteSchemaVersion(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a shared component version
   *
   * @remarks
   * Create a schema version.
   */
  async createSchemaVersion(
    request: operations.CreateSchemaVersionRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateSchemaVersionResponse> {
    return unwrapAsync(schemasCreateSchemaVersion(
      this,
      request,
      options,
    ));
  }

  /**
   * Add shared component access group
   *
   * @remarks
   * Add an access group to a schema.
   */
  async addSchemaAccessGroup(
    request: operations.AddSchemaAccessGroupRequest,
    options?: RequestOptions,
  ): Promise<operations.AddSchemaAccessGroupResponse> {
    return unwrapAsync(schemasAddSchemaAccessGroup(
      this,
      request,
      options,
    ));
  }

  /**
   * Remove shared component access group
   *
   * @remarks
   * Remove an access group from a schema.
   */
  async removeSchemaAccessGroup(
    request: operations.RemoveSchemaAccessGroupRequest,
    options?: RequestOptions,
  ): Promise<operations.RemoveSchemaAccessGroupResponse> {
    return unwrapAsync(schemasRemoveSchemaAccessGroup(
      this,
      request,
      options,
    ));
  }
}
