/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Authentication } from "./authentication.js";
import { LoginPortals } from "./loginportals.js";
import { Namespaces } from "./namespaces.js";
import { Registry } from "./registry.js";
import { Rules } from "./rules.js";
import { ScalarDocs } from "./scalardocs.js";
import { Schemas } from "./schemas.js";
import { Teams } from "./teams.js";
import { Themes } from "./themes.js";

export class Scalar extends ClientSDK {
  private _registry?: Registry;
  get registry(): Registry {
    return (this._registry ??= new Registry(this._options));
  }

  private _schemas?: Schemas;
  get schemas(): Schemas {
    return (this._schemas ??= new Schemas(this._options));
  }

  private _loginPortals?: LoginPortals;
  get loginPortals(): LoginPortals {
    return (this._loginPortals ??= new LoginPortals(this._options));
  }

  private _rules?: Rules;
  get rules(): Rules {
    return (this._rules ??= new Rules(this._options));
  }

  private _themes?: Themes;
  get themes(): Themes {
    return (this._themes ??= new Themes(this._options));
  }

  private _teams?: Teams;
  get teams(): Teams {
    return (this._teams ??= new Teams(this._options));
  }

  private _scalarDocs?: ScalarDocs;
  get scalarDocs(): ScalarDocs {
    return (this._scalarDocs ??= new ScalarDocs(this._options));
  }

  private _namespaces?: Namespaces;
  get namespaces(): Namespaces {
    return (this._namespaces ??= new Namespaces(this._options));
  }

  private _authentication?: Authentication;
  get authentication(): Authentication {
    return (this._authentication ??= new Authentication(this._options));
  }
}
