/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { teamsGetv1Teams } from "../funcs/teamsGetv1Teams.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Teams extends ClientSDK {
  /**
   * List teams
   *
   * @remarks
   * List all available teams
   */
  async getv1Teams(
    options?: RequestOptions,
  ): Promise<Array<components.Team>> {
    return unwrapAsync(teamsGetv1Teams(
      this,
      options,
    ));
  }
}
