/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { teamsListTeams } from "../funcs/teamsListTeams.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Teams extends ClientSDK {
  /**
   * List teams
   *
   * @remarks
   * List all available teams
   */
  async listTeams(
    options?: RequestOptions,
  ): Promise<operations.ListTeamsResponse> {
    return unwrapAsync(teamsListTeams(
      this,
      options,
    ));
  }
}
