/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AddApiDocumentAccessGroupRequest = {
  namespace: string;
  slug: string;
  accessGroup: components.AccessGroup;
};

/** @internal */
export const AddApiDocumentAccessGroupRequest$inboundSchema: z.ZodType<
  AddApiDocumentAccessGroupRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  namespace: z.string(),
  slug: z.string(),
  "access-group": components.AccessGroup$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "access-group": "accessGroup",
  });
});

/** @internal */
export type AddApiDocumentAccessGroupRequest$Outbound = {
  namespace: string;
  slug: string;
  "access-group": components.AccessGroup$Outbound;
};

/** @internal */
export const AddApiDocumentAccessGroupRequest$outboundSchema: z.ZodType<
  AddApiDocumentAccessGroupRequest$Outbound,
  z.ZodTypeDef,
  AddApiDocumentAccessGroupRequest
> = z.object({
  namespace: z.string(),
  slug: z.string(),
  accessGroup: components.AccessGroup$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    accessGroup: "access-group",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AddApiDocumentAccessGroupRequest$ {
  /** @deprecated use `AddApiDocumentAccessGroupRequest$inboundSchema` instead. */
  export const inboundSchema = AddApiDocumentAccessGroupRequest$inboundSchema;
  /** @deprecated use `AddApiDocumentAccessGroupRequest$outboundSchema` instead. */
  export const outboundSchema = AddApiDocumentAccessGroupRequest$outboundSchema;
  /** @deprecated use `AddApiDocumentAccessGroupRequest$Outbound` instead. */
  export type Outbound = AddApiDocumentAccessGroupRequest$Outbound;
}

export function addApiDocumentAccessGroupRequestToJSON(
  addApiDocumentAccessGroupRequest: AddApiDocumentAccessGroupRequest,
): string {
  return JSON.stringify(
    AddApiDocumentAccessGroupRequest$outboundSchema.parse(
      addApiDocumentAccessGroupRequest,
    ),
  );
}

export function addApiDocumentAccessGroupRequestFromJSON(
  jsonString: string,
): SafeParseResult<AddApiDocumentAccessGroupRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AddApiDocumentAccessGroupRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AddApiDocumentAccessGroupRequest' from JSON`,
  );
}
