/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AddRulesetAccessGroupRequest = {
  namespace: string;
  slug: string;
  accessGroup: components.AccessGroup;
};

export type AddRulesetAccessGroupResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Default Response
   */
  any?: any | null | undefined;
};

/** @internal */
export const AddRulesetAccessGroupRequest$inboundSchema: z.ZodType<
  AddRulesetAccessGroupRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  namespace: z.string(),
  slug: z.string(),
  "access-group": components.AccessGroup$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "access-group": "accessGroup",
  });
});

/** @internal */
export type AddRulesetAccessGroupRequest$Outbound = {
  namespace: string;
  slug: string;
  "access-group": components.AccessGroup$Outbound;
};

/** @internal */
export const AddRulesetAccessGroupRequest$outboundSchema: z.ZodType<
  AddRulesetAccessGroupRequest$Outbound,
  z.ZodTypeDef,
  AddRulesetAccessGroupRequest
> = z.object({
  namespace: z.string(),
  slug: z.string(),
  accessGroup: components.AccessGroup$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    accessGroup: "access-group",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AddRulesetAccessGroupRequest$ {
  /** @deprecated use `AddRulesetAccessGroupRequest$inboundSchema` instead. */
  export const inboundSchema = AddRulesetAccessGroupRequest$inboundSchema;
  /** @deprecated use `AddRulesetAccessGroupRequest$outboundSchema` instead. */
  export const outboundSchema = AddRulesetAccessGroupRequest$outboundSchema;
  /** @deprecated use `AddRulesetAccessGroupRequest$Outbound` instead. */
  export type Outbound = AddRulesetAccessGroupRequest$Outbound;
}

export function addRulesetAccessGroupRequestToJSON(
  addRulesetAccessGroupRequest: AddRulesetAccessGroupRequest,
): string {
  return JSON.stringify(
    AddRulesetAccessGroupRequest$outboundSchema.parse(
      addRulesetAccessGroupRequest,
    ),
  );
}

export function addRulesetAccessGroupRequestFromJSON(
  jsonString: string,
): SafeParseResult<AddRulesetAccessGroupRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AddRulesetAccessGroupRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AddRulesetAccessGroupRequest' from JSON`,
  );
}

/** @internal */
export const AddRulesetAccessGroupResponse$inboundSchema: z.ZodType<
  AddRulesetAccessGroupResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  any: z.nullable(z.any()).optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
  });
});

/** @internal */
export type AddRulesetAccessGroupResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  any?: any | null | undefined;
};

/** @internal */
export const AddRulesetAccessGroupResponse$outboundSchema: z.ZodType<
  AddRulesetAccessGroupResponse$Outbound,
  z.ZodTypeDef,
  AddRulesetAccessGroupResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  any: z.nullable(z.any()).optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AddRulesetAccessGroupResponse$ {
  /** @deprecated use `AddRulesetAccessGroupResponse$inboundSchema` instead. */
  export const inboundSchema = AddRulesetAccessGroupResponse$inboundSchema;
  /** @deprecated use `AddRulesetAccessGroupResponse$outboundSchema` instead. */
  export const outboundSchema = AddRulesetAccessGroupResponse$outboundSchema;
  /** @deprecated use `AddRulesetAccessGroupResponse$Outbound` instead. */
  export type Outbound = AddRulesetAccessGroupResponse$Outbound;
}

export function addRulesetAccessGroupResponseToJSON(
  addRulesetAccessGroupResponse: AddRulesetAccessGroupResponse,
): string {
  return JSON.stringify(
    AddRulesetAccessGroupResponse$outboundSchema.parse(
      addRulesetAccessGroupResponse,
    ),
  );
}

export function addRulesetAccessGroupResponseFromJSON(
  jsonString: string,
): SafeParseResult<AddRulesetAccessGroupResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AddRulesetAccessGroupResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AddRulesetAccessGroupResponse' from JSON`,
  );
}
