/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateGuideRequestBody = {
  name: string;
  slug?: string | undefined;
  isPrivate?: boolean | undefined;
  allowedUsers: Array<string>;
  allowedDomains: Array<string>;
};

/**
 * Default Response
 */
export type CreateGuideResponseBody = {
  uid: string;
  slug: string;
};

export type CreateGuideResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Default Response
   */
  object?: CreateGuideResponseBody | undefined;
};

/** @internal */
export const CreateGuideRequestBody$inboundSchema: z.ZodType<
  CreateGuideRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  slug: z.string().optional(),
  isPrivate: z.boolean().default(false),
  allowedUsers: z.array(z.string()),
  allowedDomains: z.array(z.string()),
});

/** @internal */
export type CreateGuideRequestBody$Outbound = {
  name: string;
  slug?: string | undefined;
  isPrivate: boolean;
  allowedUsers: Array<string>;
  allowedDomains: Array<string>;
};

/** @internal */
export const CreateGuideRequestBody$outboundSchema: z.ZodType<
  CreateGuideRequestBody$Outbound,
  z.ZodTypeDef,
  CreateGuideRequestBody
> = z.object({
  name: z.string(),
  slug: z.string().optional(),
  isPrivate: z.boolean().default(false),
  allowedUsers: z.array(z.string()),
  allowedDomains: z.array(z.string()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateGuideRequestBody$ {
  /** @deprecated use `CreateGuideRequestBody$inboundSchema` instead. */
  export const inboundSchema = CreateGuideRequestBody$inboundSchema;
  /** @deprecated use `CreateGuideRequestBody$outboundSchema` instead. */
  export const outboundSchema = CreateGuideRequestBody$outboundSchema;
  /** @deprecated use `CreateGuideRequestBody$Outbound` instead. */
  export type Outbound = CreateGuideRequestBody$Outbound;
}

export function createGuideRequestBodyToJSON(
  createGuideRequestBody: CreateGuideRequestBody,
): string {
  return JSON.stringify(
    CreateGuideRequestBody$outboundSchema.parse(createGuideRequestBody),
  );
}

export function createGuideRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<CreateGuideRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateGuideRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateGuideRequestBody' from JSON`,
  );
}

/** @internal */
export const CreateGuideResponseBody$inboundSchema: z.ZodType<
  CreateGuideResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  uid: z.string(),
  slug: z.string(),
});

/** @internal */
export type CreateGuideResponseBody$Outbound = {
  uid: string;
  slug: string;
};

/** @internal */
export const CreateGuideResponseBody$outboundSchema: z.ZodType<
  CreateGuideResponseBody$Outbound,
  z.ZodTypeDef,
  CreateGuideResponseBody
> = z.object({
  uid: z.string(),
  slug: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateGuideResponseBody$ {
  /** @deprecated use `CreateGuideResponseBody$inboundSchema` instead. */
  export const inboundSchema = CreateGuideResponseBody$inboundSchema;
  /** @deprecated use `CreateGuideResponseBody$outboundSchema` instead. */
  export const outboundSchema = CreateGuideResponseBody$outboundSchema;
  /** @deprecated use `CreateGuideResponseBody$Outbound` instead. */
  export type Outbound = CreateGuideResponseBody$Outbound;
}

export function createGuideResponseBodyToJSON(
  createGuideResponseBody: CreateGuideResponseBody,
): string {
  return JSON.stringify(
    CreateGuideResponseBody$outboundSchema.parse(createGuideResponseBody),
  );
}

export function createGuideResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<CreateGuideResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateGuideResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateGuideResponseBody' from JSON`,
  );
}

/** @internal */
export const CreateGuideResponse$inboundSchema: z.ZodType<
  CreateGuideResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  object: z.lazy(() => CreateGuideResponseBody$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
  });
});

/** @internal */
export type CreateGuideResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  object?: CreateGuideResponseBody$Outbound | undefined;
};

/** @internal */
export const CreateGuideResponse$outboundSchema: z.ZodType<
  CreateGuideResponse$Outbound,
  z.ZodTypeDef,
  CreateGuideResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  object: z.lazy(() => CreateGuideResponseBody$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateGuideResponse$ {
  /** @deprecated use `CreateGuideResponse$inboundSchema` instead. */
  export const inboundSchema = CreateGuideResponse$inboundSchema;
  /** @deprecated use `CreateGuideResponse$outboundSchema` instead. */
  export const outboundSchema = CreateGuideResponse$outboundSchema;
  /** @deprecated use `CreateGuideResponse$Outbound` instead. */
  export type Outbound = CreateGuideResponse$Outbound;
}

export function createGuideResponseToJSON(
  createGuideResponse: CreateGuideResponse,
): string {
  return JSON.stringify(
    CreateGuideResponse$outboundSchema.parse(createGuideResponse),
  );
}

export function createGuideResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateGuideResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateGuideResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateGuideResponse' from JSON`,
  );
}
