/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateSchemaRequestBody = {
  title: string;
  description?: string | undefined;
  version: string;
  slug: string;
  isPrivate?: boolean | undefined;
  document: string;
};

export type CreateSchemaRequest = {
  namespace: string;
  requestBody: CreateSchemaRequestBody;
};

export type CreateSchemaResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Default Response
   */
  uid?: components.Uid | undefined;
};

/** @internal */
export const CreateSchemaRequestBody$inboundSchema: z.ZodType<
  CreateSchemaRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  title: z.string(),
  description: z.string().optional(),
  version: z.string(),
  slug: z.string(),
  isPrivate: z.boolean().optional(),
  document: z.string(),
});

/** @internal */
export type CreateSchemaRequestBody$Outbound = {
  title: string;
  description?: string | undefined;
  version: string;
  slug: string;
  isPrivate?: boolean | undefined;
  document: string;
};

/** @internal */
export const CreateSchemaRequestBody$outboundSchema: z.ZodType<
  CreateSchemaRequestBody$Outbound,
  z.ZodTypeDef,
  CreateSchemaRequestBody
> = z.object({
  title: z.string(),
  description: z.string().optional(),
  version: z.string(),
  slug: z.string(),
  isPrivate: z.boolean().optional(),
  document: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateSchemaRequestBody$ {
  /** @deprecated use `CreateSchemaRequestBody$inboundSchema` instead. */
  export const inboundSchema = CreateSchemaRequestBody$inboundSchema;
  /** @deprecated use `CreateSchemaRequestBody$outboundSchema` instead. */
  export const outboundSchema = CreateSchemaRequestBody$outboundSchema;
  /** @deprecated use `CreateSchemaRequestBody$Outbound` instead. */
  export type Outbound = CreateSchemaRequestBody$Outbound;
}

export function createSchemaRequestBodyToJSON(
  createSchemaRequestBody: CreateSchemaRequestBody,
): string {
  return JSON.stringify(
    CreateSchemaRequestBody$outboundSchema.parse(createSchemaRequestBody),
  );
}

export function createSchemaRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<CreateSchemaRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateSchemaRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateSchemaRequestBody' from JSON`,
  );
}

/** @internal */
export const CreateSchemaRequest$inboundSchema: z.ZodType<
  CreateSchemaRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  namespace: z.string(),
  RequestBody: z.lazy(() => CreateSchemaRequestBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type CreateSchemaRequest$Outbound = {
  namespace: string;
  RequestBody: CreateSchemaRequestBody$Outbound;
};

/** @internal */
export const CreateSchemaRequest$outboundSchema: z.ZodType<
  CreateSchemaRequest$Outbound,
  z.ZodTypeDef,
  CreateSchemaRequest
> = z.object({
  namespace: z.string(),
  requestBody: z.lazy(() => CreateSchemaRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateSchemaRequest$ {
  /** @deprecated use `CreateSchemaRequest$inboundSchema` instead. */
  export const inboundSchema = CreateSchemaRequest$inboundSchema;
  /** @deprecated use `CreateSchemaRequest$outboundSchema` instead. */
  export const outboundSchema = CreateSchemaRequest$outboundSchema;
  /** @deprecated use `CreateSchemaRequest$Outbound` instead. */
  export type Outbound = CreateSchemaRequest$Outbound;
}

export function createSchemaRequestToJSON(
  createSchemaRequest: CreateSchemaRequest,
): string {
  return JSON.stringify(
    CreateSchemaRequest$outboundSchema.parse(createSchemaRequest),
  );
}

export function createSchemaRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateSchemaRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateSchemaRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateSchemaRequest' from JSON`,
  );
}

/** @internal */
export const CreateSchemaResponse$inboundSchema: z.ZodType<
  CreateSchemaResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  uid: components.Uid$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
  });
});

/** @internal */
export type CreateSchemaResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  uid?: components.Uid$Outbound | undefined;
};

/** @internal */
export const CreateSchemaResponse$outboundSchema: z.ZodType<
  CreateSchemaResponse$Outbound,
  z.ZodTypeDef,
  CreateSchemaResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  uid: components.Uid$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateSchemaResponse$ {
  /** @deprecated use `CreateSchemaResponse$inboundSchema` instead. */
  export const inboundSchema = CreateSchemaResponse$inboundSchema;
  /** @deprecated use `CreateSchemaResponse$outboundSchema` instead. */
  export const outboundSchema = CreateSchemaResponse$outboundSchema;
  /** @deprecated use `CreateSchemaResponse$Outbound` instead. */
  export type Outbound = CreateSchemaResponse$Outbound;
}

export function createSchemaResponseToJSON(
  createSchemaResponse: CreateSchemaResponse,
): string {
  return JSON.stringify(
    CreateSchemaResponse$outboundSchema.parse(createSchemaResponse),
  );
}

export function createSchemaResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateSchemaResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateSchemaResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateSchemaResponse' from JSON`,
  );
}
