/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateSchemaVersionRequestBody = {
  version: string;
  document: string;
};

export type CreateSchemaVersionRequest = {
  namespace: string;
  slug: string;
  requestBody: CreateSchemaVersionRequestBody;
};

/** @internal */
export const CreateSchemaVersionRequestBody$inboundSchema: z.ZodType<
  CreateSchemaVersionRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  version: z.string(),
  document: z.string(),
});

/** @internal */
export type CreateSchemaVersionRequestBody$Outbound = {
  version: string;
  document: string;
};

/** @internal */
export const CreateSchemaVersionRequestBody$outboundSchema: z.ZodType<
  CreateSchemaVersionRequestBody$Outbound,
  z.ZodTypeDef,
  CreateSchemaVersionRequestBody
> = z.object({
  version: z.string(),
  document: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateSchemaVersionRequestBody$ {
  /** @deprecated use `CreateSchemaVersionRequestBody$inboundSchema` instead. */
  export const inboundSchema = CreateSchemaVersionRequestBody$inboundSchema;
  /** @deprecated use `CreateSchemaVersionRequestBody$outboundSchema` instead. */
  export const outboundSchema = CreateSchemaVersionRequestBody$outboundSchema;
  /** @deprecated use `CreateSchemaVersionRequestBody$Outbound` instead. */
  export type Outbound = CreateSchemaVersionRequestBody$Outbound;
}

export function createSchemaVersionRequestBodyToJSON(
  createSchemaVersionRequestBody: CreateSchemaVersionRequestBody,
): string {
  return JSON.stringify(
    CreateSchemaVersionRequestBody$outboundSchema.parse(
      createSchemaVersionRequestBody,
    ),
  );
}

export function createSchemaVersionRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<CreateSchemaVersionRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateSchemaVersionRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateSchemaVersionRequestBody' from JSON`,
  );
}

/** @internal */
export const CreateSchemaVersionRequest$inboundSchema: z.ZodType<
  CreateSchemaVersionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  namespace: z.string(),
  slug: z.string(),
  RequestBody: z.lazy(() => CreateSchemaVersionRequestBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type CreateSchemaVersionRequest$Outbound = {
  namespace: string;
  slug: string;
  RequestBody: CreateSchemaVersionRequestBody$Outbound;
};

/** @internal */
export const CreateSchemaVersionRequest$outboundSchema: z.ZodType<
  CreateSchemaVersionRequest$Outbound,
  z.ZodTypeDef,
  CreateSchemaVersionRequest
> = z.object({
  namespace: z.string(),
  slug: z.string(),
  requestBody: z.lazy(() => CreateSchemaVersionRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateSchemaVersionRequest$ {
  /** @deprecated use `CreateSchemaVersionRequest$inboundSchema` instead. */
  export const inboundSchema = CreateSchemaVersionRequest$inboundSchema;
  /** @deprecated use `CreateSchemaVersionRequest$outboundSchema` instead. */
  export const outboundSchema = CreateSchemaVersionRequest$outboundSchema;
  /** @deprecated use `CreateSchemaVersionRequest$Outbound` instead. */
  export type Outbound = CreateSchemaVersionRequest$Outbound;
}

export function createSchemaVersionRequestToJSON(
  createSchemaVersionRequest: CreateSchemaVersionRequest,
): string {
  return JSON.stringify(
    CreateSchemaVersionRequest$outboundSchema.parse(createSchemaVersionRequest),
  );
}

export function createSchemaVersionRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateSchemaVersionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateSchemaVersionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateSchemaVersionRequest' from JSON`,
  );
}
