/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateRulesetRequestBody = {
  title: string;
  description?: string | undefined;
  slug: string;
  isPrivate?: boolean | undefined;
  document: string;
};

export type CreateRulesetRequest = {
  namespace: string;
  requestBody: CreateRulesetRequestBody;
};

/** @internal */
export const CreateRulesetRequestBody$inboundSchema: z.ZodType<
  CreateRulesetRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  title: z.string(),
  description: z.string().optional(),
  slug: z.string(),
  isPrivate: z.boolean().optional(),
  document: z.string(),
});

/** @internal */
export type CreateRulesetRequestBody$Outbound = {
  title: string;
  description?: string | undefined;
  slug: string;
  isPrivate?: boolean | undefined;
  document: string;
};

/** @internal */
export const CreateRulesetRequestBody$outboundSchema: z.ZodType<
  CreateRulesetRequestBody$Outbound,
  z.ZodTypeDef,
  CreateRulesetRequestBody
> = z.object({
  title: z.string(),
  description: z.string().optional(),
  slug: z.string(),
  isPrivate: z.boolean().optional(),
  document: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateRulesetRequestBody$ {
  /** @deprecated use `CreateRulesetRequestBody$inboundSchema` instead. */
  export const inboundSchema = CreateRulesetRequestBody$inboundSchema;
  /** @deprecated use `CreateRulesetRequestBody$outboundSchema` instead. */
  export const outboundSchema = CreateRulesetRequestBody$outboundSchema;
  /** @deprecated use `CreateRulesetRequestBody$Outbound` instead. */
  export type Outbound = CreateRulesetRequestBody$Outbound;
}

export function createRulesetRequestBodyToJSON(
  createRulesetRequestBody: CreateRulesetRequestBody,
): string {
  return JSON.stringify(
    CreateRulesetRequestBody$outboundSchema.parse(createRulesetRequestBody),
  );
}

export function createRulesetRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<CreateRulesetRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateRulesetRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateRulesetRequestBody' from JSON`,
  );
}

/** @internal */
export const CreateRulesetRequest$inboundSchema: z.ZodType<
  CreateRulesetRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  namespace: z.string(),
  RequestBody: z.lazy(() => CreateRulesetRequestBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type CreateRulesetRequest$Outbound = {
  namespace: string;
  RequestBody: CreateRulesetRequestBody$Outbound;
};

/** @internal */
export const CreateRulesetRequest$outboundSchema: z.ZodType<
  CreateRulesetRequest$Outbound,
  z.ZodTypeDef,
  CreateRulesetRequest
> = z.object({
  namespace: z.string(),
  requestBody: z.lazy(() => CreateRulesetRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateRulesetRequest$ {
  /** @deprecated use `CreateRulesetRequest$inboundSchema` instead. */
  export const inboundSchema = CreateRulesetRequest$inboundSchema;
  /** @deprecated use `CreateRulesetRequest$outboundSchema` instead. */
  export const outboundSchema = CreateRulesetRequest$outboundSchema;
  /** @deprecated use `CreateRulesetRequest$Outbound` instead. */
  export type Outbound = CreateRulesetRequest$Outbound;
}

export function createRulesetRequestToJSON(
  createRulesetRequest: CreateRulesetRequest,
): string {
  return JSON.stringify(
    CreateRulesetRequest$outboundSchema.parse(createRulesetRequest),
  );
}

export function createRulesetRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateRulesetRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateRulesetRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateRulesetRequest' from JSON`,
  );
}
