/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateThemeRequestBody = {
  name: string;
  description?: string | undefined;
  slug: string;
  document: string;
};

export type CreateThemeResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Default Response
   */
  uid?: components.Uid | undefined;
};

/** @internal */
export const CreateThemeRequestBody$inboundSchema: z.ZodType<
  CreateThemeRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  description: z.string().optional(),
  slug: z.string(),
  document: z.string(),
});

/** @internal */
export type CreateThemeRequestBody$Outbound = {
  name: string;
  description?: string | undefined;
  slug: string;
  document: string;
};

/** @internal */
export const CreateThemeRequestBody$outboundSchema: z.ZodType<
  CreateThemeRequestBody$Outbound,
  z.ZodTypeDef,
  CreateThemeRequestBody
> = z.object({
  name: z.string(),
  description: z.string().optional(),
  slug: z.string(),
  document: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateThemeRequestBody$ {
  /** @deprecated use `CreateThemeRequestBody$inboundSchema` instead. */
  export const inboundSchema = CreateThemeRequestBody$inboundSchema;
  /** @deprecated use `CreateThemeRequestBody$outboundSchema` instead. */
  export const outboundSchema = CreateThemeRequestBody$outboundSchema;
  /** @deprecated use `CreateThemeRequestBody$Outbound` instead. */
  export type Outbound = CreateThemeRequestBody$Outbound;
}

export function createThemeRequestBodyToJSON(
  createThemeRequestBody: CreateThemeRequestBody,
): string {
  return JSON.stringify(
    CreateThemeRequestBody$outboundSchema.parse(createThemeRequestBody),
  );
}

export function createThemeRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<CreateThemeRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateThemeRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateThemeRequestBody' from JSON`,
  );
}

/** @internal */
export const CreateThemeResponse$inboundSchema: z.ZodType<
  CreateThemeResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  uid: components.Uid$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
  });
});

/** @internal */
export type CreateThemeResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  uid?: components.Uid$Outbound | undefined;
};

/** @internal */
export const CreateThemeResponse$outboundSchema: z.ZodType<
  CreateThemeResponse$Outbound,
  z.ZodTypeDef,
  CreateThemeResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  uid: components.Uid$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateThemeResponse$ {
  /** @deprecated use `CreateThemeResponse$inboundSchema` instead. */
  export const inboundSchema = CreateThemeResponse$inboundSchema;
  /** @deprecated use `CreateThemeResponse$outboundSchema` instead. */
  export const outboundSchema = CreateThemeResponse$outboundSchema;
  /** @deprecated use `CreateThemeResponse$Outbound` instead. */
  export type Outbound = CreateThemeResponse$Outbound;
}

export function createThemeResponseToJSON(
  createThemeResponse: CreateThemeResponse,
): string {
  return JSON.stringify(
    CreateThemeResponse$outboundSchema.parse(createThemeResponse),
  );
}

export function createThemeResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateThemeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateThemeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateThemeResponse' from JSON`,
  );
}
