/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Deletev1LoginPortalsSlugRequest = {
  slug: string;
};

/** @internal */
export const Deletev1LoginPortalsSlugRequest$inboundSchema: z.ZodType<
  Deletev1LoginPortalsSlugRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  slug: z.string(),
});

/** @internal */
export type Deletev1LoginPortalsSlugRequest$Outbound = {
  slug: string;
};

/** @internal */
export const Deletev1LoginPortalsSlugRequest$outboundSchema: z.ZodType<
  Deletev1LoginPortalsSlugRequest$Outbound,
  z.ZodTypeDef,
  Deletev1LoginPortalsSlugRequest
> = z.object({
  slug: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Deletev1LoginPortalsSlugRequest$ {
  /** @deprecated use `Deletev1LoginPortalsSlugRequest$inboundSchema` instead. */
  export const inboundSchema = Deletev1LoginPortalsSlugRequest$inboundSchema;
  /** @deprecated use `Deletev1LoginPortalsSlugRequest$outboundSchema` instead. */
  export const outboundSchema = Deletev1LoginPortalsSlugRequest$outboundSchema;
  /** @deprecated use `Deletev1LoginPortalsSlugRequest$Outbound` instead. */
  export type Outbound = Deletev1LoginPortalsSlugRequest$Outbound;
}

export function deletev1LoginPortalsSlugRequestToJSON(
  deletev1LoginPortalsSlugRequest: Deletev1LoginPortalsSlugRequest,
): string {
  return JSON.stringify(
    Deletev1LoginPortalsSlugRequest$outboundSchema.parse(
      deletev1LoginPortalsSlugRequest,
    ),
  );
}

export function deletev1LoginPortalsSlugRequestFromJSON(
  jsonString: string,
): SafeParseResult<Deletev1LoginPortalsSlugRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Deletev1LoginPortalsSlugRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Deletev1LoginPortalsSlugRequest' from JSON`,
  );
}
