/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteApiDocumentVersionRequest = {
  namespace: string;
  slug: string;
  semver: string;
};

/** @internal */
export const DeleteApiDocumentVersionRequest$inboundSchema: z.ZodType<
  DeleteApiDocumentVersionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  namespace: z.string(),
  slug: z.string(),
  semver: z.string(),
});

/** @internal */
export type DeleteApiDocumentVersionRequest$Outbound = {
  namespace: string;
  slug: string;
  semver: string;
};

/** @internal */
export const DeleteApiDocumentVersionRequest$outboundSchema: z.ZodType<
  DeleteApiDocumentVersionRequest$Outbound,
  z.ZodTypeDef,
  DeleteApiDocumentVersionRequest
> = z.object({
  namespace: z.string(),
  slug: z.string(),
  semver: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteApiDocumentVersionRequest$ {
  /** @deprecated use `DeleteApiDocumentVersionRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteApiDocumentVersionRequest$inboundSchema;
  /** @deprecated use `DeleteApiDocumentVersionRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteApiDocumentVersionRequest$outboundSchema;
  /** @deprecated use `DeleteApiDocumentVersionRequest$Outbound` instead. */
  export type Outbound = DeleteApiDocumentVersionRequest$Outbound;
}

export function deleteApiDocumentVersionRequestToJSON(
  deleteApiDocumentVersionRequest: DeleteApiDocumentVersionRequest,
): string {
  return JSON.stringify(
    DeleteApiDocumentVersionRequest$outboundSchema.parse(
      deleteApiDocumentVersionRequest,
    ),
  );
}

export function deleteApiDocumentVersionRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteApiDocumentVersionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteApiDocumentVersionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteApiDocumentVersionRequest' from JSON`,
  );
}
