/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteLoginPortalRequest = {
  slug: string;
};

/** @internal */
export const DeleteLoginPortalRequest$inboundSchema: z.ZodType<
  DeleteLoginPortalRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  slug: z.string(),
});

/** @internal */
export type DeleteLoginPortalRequest$Outbound = {
  slug: string;
};

/** @internal */
export const DeleteLoginPortalRequest$outboundSchema: z.ZodType<
  DeleteLoginPortalRequest$Outbound,
  z.ZodTypeDef,
  DeleteLoginPortalRequest
> = z.object({
  slug: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteLoginPortalRequest$ {
  /** @deprecated use `DeleteLoginPortalRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteLoginPortalRequest$inboundSchema;
  /** @deprecated use `DeleteLoginPortalRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteLoginPortalRequest$outboundSchema;
  /** @deprecated use `DeleteLoginPortalRequest$Outbound` instead. */
  export type Outbound = DeleteLoginPortalRequest$Outbound;
}

export function deleteLoginPortalRequestToJSON(
  deleteLoginPortalRequest: DeleteLoginPortalRequest,
): string {
  return JSON.stringify(
    DeleteLoginPortalRequest$outboundSchema.parse(deleteLoginPortalRequest),
  );
}

export function deleteLoginPortalRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteLoginPortalRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteLoginPortalRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteLoginPortalRequest' from JSON`,
  );
}
