/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteApiDocumentRequest = {
  namespace: string;
  slug: string;
};

/** @internal */
export const DeleteApiDocumentRequest$inboundSchema: z.ZodType<
  DeleteApiDocumentRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  namespace: z.string(),
  slug: z.string(),
});

/** @internal */
export type DeleteApiDocumentRequest$Outbound = {
  namespace: string;
  slug: string;
};

/** @internal */
export const DeleteApiDocumentRequest$outboundSchema: z.ZodType<
  DeleteApiDocumentRequest$Outbound,
  z.ZodTypeDef,
  DeleteApiDocumentRequest
> = z.object({
  namespace: z.string(),
  slug: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteApiDocumentRequest$ {
  /** @deprecated use `DeleteApiDocumentRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteApiDocumentRequest$inboundSchema;
  /** @deprecated use `DeleteApiDocumentRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteApiDocumentRequest$outboundSchema;
  /** @deprecated use `DeleteApiDocumentRequest$Outbound` instead. */
  export type Outbound = DeleteApiDocumentRequest$Outbound;
}

export function deleteApiDocumentRequestToJSON(
  deleteApiDocumentRequest: DeleteApiDocumentRequest,
): string {
  return JSON.stringify(
    DeleteApiDocumentRequest$outboundSchema.parse(deleteApiDocumentRequest),
  );
}

export function deleteApiDocumentRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteApiDocumentRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteApiDocumentRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteApiDocumentRequest' from JSON`,
  );
}
