/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Deletev1ApisNamespaceSlugRequest = {
  namespace: string;
  slug: string;
};

/** @internal */
export const Deletev1ApisNamespaceSlugRequest$inboundSchema: z.ZodType<
  Deletev1ApisNamespaceSlugRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  namespace: z.string(),
  slug: z.string(),
});

/** @internal */
export type Deletev1ApisNamespaceSlugRequest$Outbound = {
  namespace: string;
  slug: string;
};

/** @internal */
export const Deletev1ApisNamespaceSlugRequest$outboundSchema: z.ZodType<
  Deletev1ApisNamespaceSlugRequest$Outbound,
  z.ZodTypeDef,
  Deletev1ApisNamespaceSlugRequest
> = z.object({
  namespace: z.string(),
  slug: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Deletev1ApisNamespaceSlugRequest$ {
  /** @deprecated use `Deletev1ApisNamespaceSlugRequest$inboundSchema` instead. */
  export const inboundSchema = Deletev1ApisNamespaceSlugRequest$inboundSchema;
  /** @deprecated use `Deletev1ApisNamespaceSlugRequest$outboundSchema` instead. */
  export const outboundSchema = Deletev1ApisNamespaceSlugRequest$outboundSchema;
  /** @deprecated use `Deletev1ApisNamespaceSlugRequest$Outbound` instead. */
  export type Outbound = Deletev1ApisNamespaceSlugRequest$Outbound;
}

export function deletev1ApisNamespaceSlugRequestToJSON(
  deletev1ApisNamespaceSlugRequest: Deletev1ApisNamespaceSlugRequest,
): string {
  return JSON.stringify(
    Deletev1ApisNamespaceSlugRequest$outboundSchema.parse(
      deletev1ApisNamespaceSlugRequest,
    ),
  );
}

export function deletev1ApisNamespaceSlugRequestFromJSON(
  jsonString: string,
): SafeParseResult<Deletev1ApisNamespaceSlugRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Deletev1ApisNamespaceSlugRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Deletev1ApisNamespaceSlugRequest' from JSON`,
  );
}
