/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Deletev1ApisNamespaceSlugVersionSemverRequest = {
  namespace: string;
  slug: string;
  semver: string;
};

/** @internal */
export const Deletev1ApisNamespaceSlugVersionSemverRequest$inboundSchema:
  z.ZodType<
    Deletev1ApisNamespaceSlugVersionSemverRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    namespace: z.string(),
    slug: z.string(),
    semver: z.string(),
  });

/** @internal */
export type Deletev1ApisNamespaceSlugVersionSemverRequest$Outbound = {
  namespace: string;
  slug: string;
  semver: string;
};

/** @internal */
export const Deletev1ApisNamespaceSlugVersionSemverRequest$outboundSchema:
  z.ZodType<
    Deletev1ApisNamespaceSlugVersionSemverRequest$Outbound,
    z.ZodTypeDef,
    Deletev1ApisNamespaceSlugVersionSemverRequest
  > = z.object({
    namespace: z.string(),
    slug: z.string(),
    semver: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Deletev1ApisNamespaceSlugVersionSemverRequest$ {
  /** @deprecated use `Deletev1ApisNamespaceSlugVersionSemverRequest$inboundSchema` instead. */
  export const inboundSchema =
    Deletev1ApisNamespaceSlugVersionSemverRequest$inboundSchema;
  /** @deprecated use `Deletev1ApisNamespaceSlugVersionSemverRequest$outboundSchema` instead. */
  export const outboundSchema =
    Deletev1ApisNamespaceSlugVersionSemverRequest$outboundSchema;
  /** @deprecated use `Deletev1ApisNamespaceSlugVersionSemverRequest$Outbound` instead. */
  export type Outbound = Deletev1ApisNamespaceSlugVersionSemverRequest$Outbound;
}

export function deletev1ApisNamespaceSlugVersionSemverRequestToJSON(
  deletev1ApisNamespaceSlugVersionSemverRequest:
    Deletev1ApisNamespaceSlugVersionSemverRequest,
): string {
  return JSON.stringify(
    Deletev1ApisNamespaceSlugVersionSemverRequest$outboundSchema.parse(
      deletev1ApisNamespaceSlugVersionSemverRequest,
    ),
  );
}

export function deletev1ApisNamespaceSlugVersionSemverRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  Deletev1ApisNamespaceSlugVersionSemverRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      Deletev1ApisNamespaceSlugVersionSemverRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'Deletev1ApisNamespaceSlugVersionSemverRequest' from JSON`,
  );
}
