/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteSchemaRequest = {
  namespace: string;
  slug: string;
};

/** @internal */
export const DeleteSchemaRequest$inboundSchema: z.ZodType<
  DeleteSchemaRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  namespace: z.string(),
  slug: z.string(),
});

/** @internal */
export type DeleteSchemaRequest$Outbound = {
  namespace: string;
  slug: string;
};

/** @internal */
export const DeleteSchemaRequest$outboundSchema: z.ZodType<
  DeleteSchemaRequest$Outbound,
  z.ZodTypeDef,
  DeleteSchemaRequest
> = z.object({
  namespace: z.string(),
  slug: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteSchemaRequest$ {
  /** @deprecated use `DeleteSchemaRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteSchemaRequest$inboundSchema;
  /** @deprecated use `DeleteSchemaRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteSchemaRequest$outboundSchema;
  /** @deprecated use `DeleteSchemaRequest$Outbound` instead. */
  export type Outbound = DeleteSchemaRequest$Outbound;
}

export function deleteSchemaRequestToJSON(
  deleteSchemaRequest: DeleteSchemaRequest,
): string {
  return JSON.stringify(
    DeleteSchemaRequest$outboundSchema.parse(deleteSchemaRequest),
  );
}

export function deleteSchemaRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteSchemaRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteSchemaRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteSchemaRequest' from JSON`,
  );
}
