/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteRulesetRequest = {
  namespace: string;
  slug: string;
};

/** @internal */
export const DeleteRulesetRequest$inboundSchema: z.ZodType<
  DeleteRulesetRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  namespace: z.string(),
  slug: z.string(),
});

/** @internal */
export type DeleteRulesetRequest$Outbound = {
  namespace: string;
  slug: string;
};

/** @internal */
export const DeleteRulesetRequest$outboundSchema: z.ZodType<
  DeleteRulesetRequest$Outbound,
  z.ZodTypeDef,
  DeleteRulesetRequest
> = z.object({
  namespace: z.string(),
  slug: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteRulesetRequest$ {
  /** @deprecated use `DeleteRulesetRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteRulesetRequest$inboundSchema;
  /** @deprecated use `DeleteRulesetRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteRulesetRequest$outboundSchema;
  /** @deprecated use `DeleteRulesetRequest$Outbound` instead. */
  export type Outbound = DeleteRulesetRequest$Outbound;
}

export function deleteRulesetRequestToJSON(
  deleteRulesetRequest: DeleteRulesetRequest,
): string {
  return JSON.stringify(
    DeleteRulesetRequest$outboundSchema.parse(deleteRulesetRequest),
  );
}

export function deleteRulesetRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteRulesetRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteRulesetRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteRulesetRequest' from JSON`,
  );
}
