/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteApiDocumentRequest = {
  namespace: string;
  slug: string;
};

export type DeleteApiDocumentResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Default Response
   */
  any?: any | null | undefined;
};

/** @internal */
export const DeleteApiDocumentRequest$inboundSchema: z.ZodType<
  DeleteApiDocumentRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  namespace: z.string(),
  slug: z.string(),
});

/** @internal */
export type DeleteApiDocumentRequest$Outbound = {
  namespace: string;
  slug: string;
};

/** @internal */
export const DeleteApiDocumentRequest$outboundSchema: z.ZodType<
  DeleteApiDocumentRequest$Outbound,
  z.ZodTypeDef,
  DeleteApiDocumentRequest
> = z.object({
  namespace: z.string(),
  slug: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteApiDocumentRequest$ {
  /** @deprecated use `DeleteApiDocumentRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteApiDocumentRequest$inboundSchema;
  /** @deprecated use `DeleteApiDocumentRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteApiDocumentRequest$outboundSchema;
  /** @deprecated use `DeleteApiDocumentRequest$Outbound` instead. */
  export type Outbound = DeleteApiDocumentRequest$Outbound;
}

export function deleteApiDocumentRequestToJSON(
  deleteApiDocumentRequest: DeleteApiDocumentRequest,
): string {
  return JSON.stringify(
    DeleteApiDocumentRequest$outboundSchema.parse(deleteApiDocumentRequest),
  );
}

export function deleteApiDocumentRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteApiDocumentRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteApiDocumentRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteApiDocumentRequest' from JSON`,
  );
}

/** @internal */
export const DeleteApiDocumentResponse$inboundSchema: z.ZodType<
  DeleteApiDocumentResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  any: z.nullable(z.any()).optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
  });
});

/** @internal */
export type DeleteApiDocumentResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  any?: any | null | undefined;
};

/** @internal */
export const DeleteApiDocumentResponse$outboundSchema: z.ZodType<
  DeleteApiDocumentResponse$Outbound,
  z.ZodTypeDef,
  DeleteApiDocumentResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  any: z.nullable(z.any()).optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteApiDocumentResponse$ {
  /** @deprecated use `DeleteApiDocumentResponse$inboundSchema` instead. */
  export const inboundSchema = DeleteApiDocumentResponse$inboundSchema;
  /** @deprecated use `DeleteApiDocumentResponse$outboundSchema` instead. */
  export const outboundSchema = DeleteApiDocumentResponse$outboundSchema;
  /** @deprecated use `DeleteApiDocumentResponse$Outbound` instead. */
  export type Outbound = DeleteApiDocumentResponse$Outbound;
}

export function deleteApiDocumentResponseToJSON(
  deleteApiDocumentResponse: DeleteApiDocumentResponse,
): string {
  return JSON.stringify(
    DeleteApiDocumentResponse$outboundSchema.parse(deleteApiDocumentResponse),
  );
}

export function deleteApiDocumentResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteApiDocumentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteApiDocumentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteApiDocumentResponse' from JSON`,
  );
}
