/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteThemeRequest = {
  slug: string;
};

/** @internal */
export const DeleteThemeRequest$inboundSchema: z.ZodType<
  DeleteThemeRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  slug: z.string(),
});

/** @internal */
export type DeleteThemeRequest$Outbound = {
  slug: string;
};

/** @internal */
export const DeleteThemeRequest$outboundSchema: z.ZodType<
  DeleteThemeRequest$Outbound,
  z.ZodTypeDef,
  DeleteThemeRequest
> = z.object({
  slug: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteThemeRequest$ {
  /** @deprecated use `DeleteThemeRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteThemeRequest$inboundSchema;
  /** @deprecated use `DeleteThemeRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteThemeRequest$outboundSchema;
  /** @deprecated use `DeleteThemeRequest$Outbound` instead. */
  export type Outbound = DeleteThemeRequest$Outbound;
}

export function deleteThemeRequestToJSON(
  deleteThemeRequest: DeleteThemeRequest,
): string {
  return JSON.stringify(
    DeleteThemeRequest$outboundSchema.parse(deleteThemeRequest),
  );
}

export function deleteThemeRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteThemeRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteThemeRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteThemeRequest' from JSON`,
  );
}
