/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteLoginPortalRequest = {
  slug: string;
};

export type DeleteLoginPortalResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Default Response
   */
  any?: any | null | undefined;
};

/** @internal */
export const DeleteLoginPortalRequest$inboundSchema: z.ZodType<
  DeleteLoginPortalRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  slug: z.string(),
});

/** @internal */
export type DeleteLoginPortalRequest$Outbound = {
  slug: string;
};

/** @internal */
export const DeleteLoginPortalRequest$outboundSchema: z.ZodType<
  DeleteLoginPortalRequest$Outbound,
  z.ZodTypeDef,
  DeleteLoginPortalRequest
> = z.object({
  slug: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteLoginPortalRequest$ {
  /** @deprecated use `DeleteLoginPortalRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteLoginPortalRequest$inboundSchema;
  /** @deprecated use `DeleteLoginPortalRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteLoginPortalRequest$outboundSchema;
  /** @deprecated use `DeleteLoginPortalRequest$Outbound` instead. */
  export type Outbound = DeleteLoginPortalRequest$Outbound;
}

export function deleteLoginPortalRequestToJSON(
  deleteLoginPortalRequest: DeleteLoginPortalRequest,
): string {
  return JSON.stringify(
    DeleteLoginPortalRequest$outboundSchema.parse(deleteLoginPortalRequest),
  );
}

export function deleteLoginPortalRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteLoginPortalRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteLoginPortalRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteLoginPortalRequest' from JSON`,
  );
}

/** @internal */
export const DeleteLoginPortalResponse$inboundSchema: z.ZodType<
  DeleteLoginPortalResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  any: z.nullable(z.any()).optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
  });
});

/** @internal */
export type DeleteLoginPortalResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  any?: any | null | undefined;
};

/** @internal */
export const DeleteLoginPortalResponse$outboundSchema: z.ZodType<
  DeleteLoginPortalResponse$Outbound,
  z.ZodTypeDef,
  DeleteLoginPortalResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  any: z.nullable(z.any()).optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteLoginPortalResponse$ {
  /** @deprecated use `DeleteLoginPortalResponse$inboundSchema` instead. */
  export const inboundSchema = DeleteLoginPortalResponse$inboundSchema;
  /** @deprecated use `DeleteLoginPortalResponse$outboundSchema` instead. */
  export const outboundSchema = DeleteLoginPortalResponse$outboundSchema;
  /** @deprecated use `DeleteLoginPortalResponse$Outbound` instead. */
  export type Outbound = DeleteLoginPortalResponse$Outbound;
}

export function deleteLoginPortalResponseToJSON(
  deleteLoginPortalResponse: DeleteLoginPortalResponse,
): string {
  return JSON.stringify(
    DeleteLoginPortalResponse$outboundSchema.parse(deleteLoginPortalResponse),
  );
}

export function deleteLoginPortalResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteLoginPortalResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteLoginPortalResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteLoginPortalResponse' from JSON`,
  );
}
