/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteSchemaVersionRequest = {
  namespace: string;
  slug: string;
  semver: string;
};

/** @internal */
export const DeleteSchemaVersionRequest$inboundSchema: z.ZodType<
  DeleteSchemaVersionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  namespace: z.string(),
  slug: z.string(),
  semver: z.string(),
});

/** @internal */
export type DeleteSchemaVersionRequest$Outbound = {
  namespace: string;
  slug: string;
  semver: string;
};

/** @internal */
export const DeleteSchemaVersionRequest$outboundSchema: z.ZodType<
  DeleteSchemaVersionRequest$Outbound,
  z.ZodTypeDef,
  DeleteSchemaVersionRequest
> = z.object({
  namespace: z.string(),
  slug: z.string(),
  semver: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteSchemaVersionRequest$ {
  /** @deprecated use `DeleteSchemaVersionRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteSchemaVersionRequest$inboundSchema;
  /** @deprecated use `DeleteSchemaVersionRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteSchemaVersionRequest$outboundSchema;
  /** @deprecated use `DeleteSchemaVersionRequest$Outbound` instead. */
  export type Outbound = DeleteSchemaVersionRequest$Outbound;
}

export function deleteSchemaVersionRequestToJSON(
  deleteSchemaVersionRequest: DeleteSchemaVersionRequest,
): string {
  return JSON.stringify(
    DeleteSchemaVersionRequest$outboundSchema.parse(deleteSchemaVersionRequest),
  );
}

export function deleteSchemaVersionRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteSchemaVersionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteSchemaVersionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteSchemaVersionRequest' from JSON`,
  );
}
