/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetApiDocumentVersionRequest = {
  namespace: string;
  slug: string;
  semver: string;
};

export type GetApiDocumentVersionResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Default Response
   */
  res?: string | undefined;
};

/** @internal */
export const GetApiDocumentVersionRequest$inboundSchema: z.ZodType<
  GetApiDocumentVersionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  namespace: z.string(),
  slug: z.string(),
  semver: z.string(),
});

/** @internal */
export type GetApiDocumentVersionRequest$Outbound = {
  namespace: string;
  slug: string;
  semver: string;
};

/** @internal */
export const GetApiDocumentVersionRequest$outboundSchema: z.ZodType<
  GetApiDocumentVersionRequest$Outbound,
  z.ZodTypeDef,
  GetApiDocumentVersionRequest
> = z.object({
  namespace: z.string(),
  slug: z.string(),
  semver: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetApiDocumentVersionRequest$ {
  /** @deprecated use `GetApiDocumentVersionRequest$inboundSchema` instead. */
  export const inboundSchema = GetApiDocumentVersionRequest$inboundSchema;
  /** @deprecated use `GetApiDocumentVersionRequest$outboundSchema` instead. */
  export const outboundSchema = GetApiDocumentVersionRequest$outboundSchema;
  /** @deprecated use `GetApiDocumentVersionRequest$Outbound` instead. */
  export type Outbound = GetApiDocumentVersionRequest$Outbound;
}

export function getApiDocumentVersionRequestToJSON(
  getApiDocumentVersionRequest: GetApiDocumentVersionRequest,
): string {
  return JSON.stringify(
    GetApiDocumentVersionRequest$outboundSchema.parse(
      getApiDocumentVersionRequest,
    ),
  );
}

export function getApiDocumentVersionRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetApiDocumentVersionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiDocumentVersionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiDocumentVersionRequest' from JSON`,
  );
}

/** @internal */
export const GetApiDocumentVersionResponse$inboundSchema: z.ZodType<
  GetApiDocumentVersionResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  res: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
  });
});

/** @internal */
export type GetApiDocumentVersionResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  res?: string | undefined;
};

/** @internal */
export const GetApiDocumentVersionResponse$outboundSchema: z.ZodType<
  GetApiDocumentVersionResponse$Outbound,
  z.ZodTypeDef,
  GetApiDocumentVersionResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  res: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetApiDocumentVersionResponse$ {
  /** @deprecated use `GetApiDocumentVersionResponse$inboundSchema` instead. */
  export const inboundSchema = GetApiDocumentVersionResponse$inboundSchema;
  /** @deprecated use `GetApiDocumentVersionResponse$outboundSchema` instead. */
  export const outboundSchema = GetApiDocumentVersionResponse$outboundSchema;
  /** @deprecated use `GetApiDocumentVersionResponse$Outbound` instead. */
  export type Outbound = GetApiDocumentVersionResponse$Outbound;
}

export function getApiDocumentVersionResponseToJSON(
  getApiDocumentVersionResponse: GetApiDocumentVersionResponse,
): string {
  return JSON.stringify(
    GetApiDocumentVersionResponse$outboundSchema.parse(
      getApiDocumentVersionResponse,
    ),
  );
}

export function getApiDocumentVersionResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetApiDocumentVersionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetApiDocumentVersionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetApiDocumentVersionResponse' from JSON`,
  );
}
