/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetCurrentUserResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Default Response
   */
  user?: components.User | undefined;
};

/** @internal */
export const GetCurrentUserResponse$inboundSchema: z.ZodType<
  GetCurrentUserResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  user: components.User$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
  });
});

/** @internal */
export type GetCurrentUserResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  user?: components.User$Outbound | undefined;
};

/** @internal */
export const GetCurrentUserResponse$outboundSchema: z.ZodType<
  GetCurrentUserResponse$Outbound,
  z.ZodTypeDef,
  GetCurrentUserResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  user: components.User$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCurrentUserResponse$ {
  /** @deprecated use `GetCurrentUserResponse$inboundSchema` instead. */
  export const inboundSchema = GetCurrentUserResponse$inboundSchema;
  /** @deprecated use `GetCurrentUserResponse$outboundSchema` instead. */
  export const outboundSchema = GetCurrentUserResponse$outboundSchema;
  /** @deprecated use `GetCurrentUserResponse$Outbound` instead. */
  export type Outbound = GetCurrentUserResponse$Outbound;
}

export function getCurrentUserResponseToJSON(
  getCurrentUserResponse: GetCurrentUserResponse,
): string {
  return JSON.stringify(
    GetCurrentUserResponse$outboundSchema.parse(getCurrentUserResponse),
  );
}

export function getCurrentUserResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetCurrentUserResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCurrentUserResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCurrentUserResponse' from JSON`,
  );
}
