/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetLoginPortalRequest = {
  slug: string;
};

/**
 * Default Response
 */
export type GetLoginPortalResponseBody = {
  uid: string;
  title: string;
  slug: string;
  email: components.LoginPortalEmail;
  page: components.LoginPortalPage;
};

/** @internal */
export const GetLoginPortalRequest$inboundSchema: z.ZodType<
  GetLoginPortalRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  slug: z.string(),
});

/** @internal */
export type GetLoginPortalRequest$Outbound = {
  slug: string;
};

/** @internal */
export const GetLoginPortalRequest$outboundSchema: z.ZodType<
  GetLoginPortalRequest$Outbound,
  z.ZodTypeDef,
  GetLoginPortalRequest
> = z.object({
  slug: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetLoginPortalRequest$ {
  /** @deprecated use `GetLoginPortalRequest$inboundSchema` instead. */
  export const inboundSchema = GetLoginPortalRequest$inboundSchema;
  /** @deprecated use `GetLoginPortalRequest$outboundSchema` instead. */
  export const outboundSchema = GetLoginPortalRequest$outboundSchema;
  /** @deprecated use `GetLoginPortalRequest$Outbound` instead. */
  export type Outbound = GetLoginPortalRequest$Outbound;
}

export function getLoginPortalRequestToJSON(
  getLoginPortalRequest: GetLoginPortalRequest,
): string {
  return JSON.stringify(
    GetLoginPortalRequest$outboundSchema.parse(getLoginPortalRequest),
  );
}

export function getLoginPortalRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetLoginPortalRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetLoginPortalRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetLoginPortalRequest' from JSON`,
  );
}

/** @internal */
export const GetLoginPortalResponseBody$inboundSchema: z.ZodType<
  GetLoginPortalResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  uid: z.string(),
  title: z.string(),
  slug: z.string(),
  email: components.LoginPortalEmail$inboundSchema,
  page: components.LoginPortalPage$inboundSchema,
});

/** @internal */
export type GetLoginPortalResponseBody$Outbound = {
  uid: string;
  title: string;
  slug: string;
  email: components.LoginPortalEmail$Outbound;
  page: components.LoginPortalPage$Outbound;
};

/** @internal */
export const GetLoginPortalResponseBody$outboundSchema: z.ZodType<
  GetLoginPortalResponseBody$Outbound,
  z.ZodTypeDef,
  GetLoginPortalResponseBody
> = z.object({
  uid: z.string(),
  title: z.string(),
  slug: z.string(),
  email: components.LoginPortalEmail$outboundSchema,
  page: components.LoginPortalPage$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetLoginPortalResponseBody$ {
  /** @deprecated use `GetLoginPortalResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetLoginPortalResponseBody$inboundSchema;
  /** @deprecated use `GetLoginPortalResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetLoginPortalResponseBody$outboundSchema;
  /** @deprecated use `GetLoginPortalResponseBody$Outbound` instead. */
  export type Outbound = GetLoginPortalResponseBody$Outbound;
}

export function getLoginPortalResponseBodyToJSON(
  getLoginPortalResponseBody: GetLoginPortalResponseBody,
): string {
  return JSON.stringify(
    GetLoginPortalResponseBody$outboundSchema.parse(getLoginPortalResponseBody),
  );
}

export function getLoginPortalResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetLoginPortalResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetLoginPortalResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetLoginPortalResponseBody' from JSON`,
  );
}
