/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetRulesetDocumentRequest = {
  namespace: string;
  slug: string;
};

export type GetRulesetDocumentResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Default Response
   */
  res?: string | undefined;
};

/** @internal */
export const GetRulesetDocumentRequest$inboundSchema: z.ZodType<
  GetRulesetDocumentRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  namespace: z.string(),
  slug: z.string(),
});

/** @internal */
export type GetRulesetDocumentRequest$Outbound = {
  namespace: string;
  slug: string;
};

/** @internal */
export const GetRulesetDocumentRequest$outboundSchema: z.ZodType<
  GetRulesetDocumentRequest$Outbound,
  z.ZodTypeDef,
  GetRulesetDocumentRequest
> = z.object({
  namespace: z.string(),
  slug: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetRulesetDocumentRequest$ {
  /** @deprecated use `GetRulesetDocumentRequest$inboundSchema` instead. */
  export const inboundSchema = GetRulesetDocumentRequest$inboundSchema;
  /** @deprecated use `GetRulesetDocumentRequest$outboundSchema` instead. */
  export const outboundSchema = GetRulesetDocumentRequest$outboundSchema;
  /** @deprecated use `GetRulesetDocumentRequest$Outbound` instead. */
  export type Outbound = GetRulesetDocumentRequest$Outbound;
}

export function getRulesetDocumentRequestToJSON(
  getRulesetDocumentRequest: GetRulesetDocumentRequest,
): string {
  return JSON.stringify(
    GetRulesetDocumentRequest$outboundSchema.parse(getRulesetDocumentRequest),
  );
}

export function getRulesetDocumentRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetRulesetDocumentRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetRulesetDocumentRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetRulesetDocumentRequest' from JSON`,
  );
}

/** @internal */
export const GetRulesetDocumentResponse$inboundSchema: z.ZodType<
  GetRulesetDocumentResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  res: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
  });
});

/** @internal */
export type GetRulesetDocumentResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  res?: string | undefined;
};

/** @internal */
export const GetRulesetDocumentResponse$outboundSchema: z.ZodType<
  GetRulesetDocumentResponse$Outbound,
  z.ZodTypeDef,
  GetRulesetDocumentResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  res: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetRulesetDocumentResponse$ {
  /** @deprecated use `GetRulesetDocumentResponse$inboundSchema` instead. */
  export const inboundSchema = GetRulesetDocumentResponse$inboundSchema;
  /** @deprecated use `GetRulesetDocumentResponse$outboundSchema` instead. */
  export const outboundSchema = GetRulesetDocumentResponse$outboundSchema;
  /** @deprecated use `GetRulesetDocumentResponse$Outbound` instead. */
  export type Outbound = GetRulesetDocumentResponse$Outbound;
}

export function getRulesetDocumentResponseToJSON(
  getRulesetDocumentResponse: GetRulesetDocumentResponse,
): string {
  return JSON.stringify(
    GetRulesetDocumentResponse$outboundSchema.parse(getRulesetDocumentResponse),
  );
}

export function getRulesetDocumentResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetRulesetDocumentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetRulesetDocumentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetRulesetDocumentResponse' from JSON`,
  );
}
