/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetSchemaVersionRequest = {
  namespace: string;
  slug: string;
  semver: string;
};

export type GetSchemaVersionResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Default Response
   */
  res?: string | undefined;
};

/** @internal */
export const GetSchemaVersionRequest$inboundSchema: z.ZodType<
  GetSchemaVersionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  namespace: z.string(),
  slug: z.string(),
  semver: z.string(),
});

/** @internal */
export type GetSchemaVersionRequest$Outbound = {
  namespace: string;
  slug: string;
  semver: string;
};

/** @internal */
export const GetSchemaVersionRequest$outboundSchema: z.ZodType<
  GetSchemaVersionRequest$Outbound,
  z.ZodTypeDef,
  GetSchemaVersionRequest
> = z.object({
  namespace: z.string(),
  slug: z.string(),
  semver: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetSchemaVersionRequest$ {
  /** @deprecated use `GetSchemaVersionRequest$inboundSchema` instead. */
  export const inboundSchema = GetSchemaVersionRequest$inboundSchema;
  /** @deprecated use `GetSchemaVersionRequest$outboundSchema` instead. */
  export const outboundSchema = GetSchemaVersionRequest$outboundSchema;
  /** @deprecated use `GetSchemaVersionRequest$Outbound` instead. */
  export type Outbound = GetSchemaVersionRequest$Outbound;
}

export function getSchemaVersionRequestToJSON(
  getSchemaVersionRequest: GetSchemaVersionRequest,
): string {
  return JSON.stringify(
    GetSchemaVersionRequest$outboundSchema.parse(getSchemaVersionRequest),
  );
}

export function getSchemaVersionRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetSchemaVersionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSchemaVersionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSchemaVersionRequest' from JSON`,
  );
}

/** @internal */
export const GetSchemaVersionResponse$inboundSchema: z.ZodType<
  GetSchemaVersionResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  res: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
  });
});

/** @internal */
export type GetSchemaVersionResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  res?: string | undefined;
};

/** @internal */
export const GetSchemaVersionResponse$outboundSchema: z.ZodType<
  GetSchemaVersionResponse$Outbound,
  z.ZodTypeDef,
  GetSchemaVersionResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  res: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetSchemaVersionResponse$ {
  /** @deprecated use `GetSchemaVersionResponse$inboundSchema` instead. */
  export const inboundSchema = GetSchemaVersionResponse$inboundSchema;
  /** @deprecated use `GetSchemaVersionResponse$outboundSchema` instead. */
  export const outboundSchema = GetSchemaVersionResponse$outboundSchema;
  /** @deprecated use `GetSchemaVersionResponse$Outbound` instead. */
  export type Outbound = GetSchemaVersionResponse$Outbound;
}

export function getSchemaVersionResponseToJSON(
  getSchemaVersionResponse: GetSchemaVersionResponse,
): string {
  return JSON.stringify(
    GetSchemaVersionResponse$outboundSchema.parse(getSchemaVersionResponse),
  );
}

export function getSchemaVersionResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetSchemaVersionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSchemaVersionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSchemaVersionResponse' from JSON`,
  );
}
