/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetSchemaVersionRequest = {
  namespace: string;
  slug: string;
  semver: string;
};

/** @internal */
export const GetSchemaVersionRequest$inboundSchema: z.ZodType<
  GetSchemaVersionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  namespace: z.string(),
  slug: z.string(),
  semver: z.string(),
});

/** @internal */
export type GetSchemaVersionRequest$Outbound = {
  namespace: string;
  slug: string;
  semver: string;
};

/** @internal */
export const GetSchemaVersionRequest$outboundSchema: z.ZodType<
  GetSchemaVersionRequest$Outbound,
  z.ZodTypeDef,
  GetSchemaVersionRequest
> = z.object({
  namespace: z.string(),
  slug: z.string(),
  semver: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetSchemaVersionRequest$ {
  /** @deprecated use `GetSchemaVersionRequest$inboundSchema` instead. */
  export const inboundSchema = GetSchemaVersionRequest$inboundSchema;
  /** @deprecated use `GetSchemaVersionRequest$outboundSchema` instead. */
  export const outboundSchema = GetSchemaVersionRequest$outboundSchema;
  /** @deprecated use `GetSchemaVersionRequest$Outbound` instead. */
  export type Outbound = GetSchemaVersionRequest$Outbound;
}

export function getSchemaVersionRequestToJSON(
  getSchemaVersionRequest: GetSchemaVersionRequest,
): string {
  return JSON.stringify(
    GetSchemaVersionRequest$outboundSchema.parse(getSchemaVersionRequest),
  );
}

export function getSchemaVersionRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetSchemaVersionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSchemaVersionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSchemaVersionRequest' from JSON`,
  );
}
