/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetThemeRequest = {
  slug: string;
};

/** @internal */
export const GetThemeRequest$inboundSchema: z.ZodType<
  GetThemeRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  slug: z.string(),
});

/** @internal */
export type GetThemeRequest$Outbound = {
  slug: string;
};

/** @internal */
export const GetThemeRequest$outboundSchema: z.ZodType<
  GetThemeRequest$Outbound,
  z.ZodTypeDef,
  GetThemeRequest
> = z.object({
  slug: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetThemeRequest$ {
  /** @deprecated use `GetThemeRequest$inboundSchema` instead. */
  export const inboundSchema = GetThemeRequest$inboundSchema;
  /** @deprecated use `GetThemeRequest$outboundSchema` instead. */
  export const outboundSchema = GetThemeRequest$outboundSchema;
  /** @deprecated use `GetThemeRequest$Outbound` instead. */
  export type Outbound = GetThemeRequest$Outbound;
}

export function getThemeRequestToJSON(
  getThemeRequest: GetThemeRequest,
): string {
  return JSON.stringify(GetThemeRequest$outboundSchema.parse(getThemeRequest));
}

export function getThemeRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetThemeRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetThemeRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetThemeRequest' from JSON`,
  );
}
