/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetThemeRequest = {
  slug: string;
};

export type GetThemeResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Default Response
   */
  res?: string | undefined;
};

/** @internal */
export const GetThemeRequest$inboundSchema: z.ZodType<
  GetThemeRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  slug: z.string(),
});

/** @internal */
export type GetThemeRequest$Outbound = {
  slug: string;
};

/** @internal */
export const GetThemeRequest$outboundSchema: z.ZodType<
  GetThemeRequest$Outbound,
  z.ZodTypeDef,
  GetThemeRequest
> = z.object({
  slug: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetThemeRequest$ {
  /** @deprecated use `GetThemeRequest$inboundSchema` instead. */
  export const inboundSchema = GetThemeRequest$inboundSchema;
  /** @deprecated use `GetThemeRequest$outboundSchema` instead. */
  export const outboundSchema = GetThemeRequest$outboundSchema;
  /** @deprecated use `GetThemeRequest$Outbound` instead. */
  export type Outbound = GetThemeRequest$Outbound;
}

export function getThemeRequestToJSON(
  getThemeRequest: GetThemeRequest,
): string {
  return JSON.stringify(GetThemeRequest$outboundSchema.parse(getThemeRequest));
}

export function getThemeRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetThemeRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetThemeRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetThemeRequest' from JSON`,
  );
}

/** @internal */
export const GetThemeResponse$inboundSchema: z.ZodType<
  GetThemeResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  res: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
  });
});

/** @internal */
export type GetThemeResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  res?: string | undefined;
};

/** @internal */
export const GetThemeResponse$outboundSchema: z.ZodType<
  GetThemeResponse$Outbound,
  z.ZodTypeDef,
  GetThemeResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  res: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetThemeResponse$ {
  /** @deprecated use `GetThemeResponse$inboundSchema` instead. */
  export const inboundSchema = GetThemeResponse$inboundSchema;
  /** @deprecated use `GetThemeResponse$outboundSchema` instead. */
  export const outboundSchema = GetThemeResponse$outboundSchema;
  /** @deprecated use `GetThemeResponse$Outbound` instead. */
  export type Outbound = GetThemeResponse$Outbound;
}

export function getThemeResponseToJSON(
  getThemeResponse: GetThemeResponse,
): string {
  return JSON.stringify(
    GetThemeResponse$outboundSchema.parse(getThemeResponse),
  );
}

export function getThemeResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetThemeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetThemeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetThemeResponse' from JSON`,
  );
}
