/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Getv1ApisNamespaceSlugVersionSemverRequest = {
  namespace: string;
  slug: string;
  semver: string;
};

/** @internal */
export const Getv1ApisNamespaceSlugVersionSemverRequest$inboundSchema:
  z.ZodType<Getv1ApisNamespaceSlugVersionSemverRequest, z.ZodTypeDef, unknown> =
    z.object({
      namespace: z.string(),
      slug: z.string(),
      semver: z.string(),
    });

/** @internal */
export type Getv1ApisNamespaceSlugVersionSemverRequest$Outbound = {
  namespace: string;
  slug: string;
  semver: string;
};

/** @internal */
export const Getv1ApisNamespaceSlugVersionSemverRequest$outboundSchema:
  z.ZodType<
    Getv1ApisNamespaceSlugVersionSemverRequest$Outbound,
    z.ZodTypeDef,
    Getv1ApisNamespaceSlugVersionSemverRequest
  > = z.object({
    namespace: z.string(),
    slug: z.string(),
    semver: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Getv1ApisNamespaceSlugVersionSemverRequest$ {
  /** @deprecated use `Getv1ApisNamespaceSlugVersionSemverRequest$inboundSchema` instead. */
  export const inboundSchema =
    Getv1ApisNamespaceSlugVersionSemverRequest$inboundSchema;
  /** @deprecated use `Getv1ApisNamespaceSlugVersionSemverRequest$outboundSchema` instead. */
  export const outboundSchema =
    Getv1ApisNamespaceSlugVersionSemverRequest$outboundSchema;
  /** @deprecated use `Getv1ApisNamespaceSlugVersionSemverRequest$Outbound` instead. */
  export type Outbound = Getv1ApisNamespaceSlugVersionSemverRequest$Outbound;
}

export function getv1ApisNamespaceSlugVersionSemverRequestToJSON(
  getv1ApisNamespaceSlugVersionSemverRequest:
    Getv1ApisNamespaceSlugVersionSemverRequest,
): string {
  return JSON.stringify(
    Getv1ApisNamespaceSlugVersionSemverRequest$outboundSchema.parse(
      getv1ApisNamespaceSlugVersionSemverRequest,
    ),
  );
}

export function getv1ApisNamespaceSlugVersionSemverRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  Getv1ApisNamespaceSlugVersionSemverRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      Getv1ApisNamespaceSlugVersionSemverRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'Getv1ApisNamespaceSlugVersionSemverRequest' from JSON`,
  );
}
