/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Getv1ApisNamespaceRequest = {
  namespace: string;
};

/** @internal */
export const Getv1ApisNamespaceRequest$inboundSchema: z.ZodType<
  Getv1ApisNamespaceRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  namespace: z.string(),
});

/** @internal */
export type Getv1ApisNamespaceRequest$Outbound = {
  namespace: string;
};

/** @internal */
export const Getv1ApisNamespaceRequest$outboundSchema: z.ZodType<
  Getv1ApisNamespaceRequest$Outbound,
  z.ZodTypeDef,
  Getv1ApisNamespaceRequest
> = z.object({
  namespace: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Getv1ApisNamespaceRequest$ {
  /** @deprecated use `Getv1ApisNamespaceRequest$inboundSchema` instead. */
  export const inboundSchema = Getv1ApisNamespaceRequest$inboundSchema;
  /** @deprecated use `Getv1ApisNamespaceRequest$outboundSchema` instead. */
  export const outboundSchema = Getv1ApisNamespaceRequest$outboundSchema;
  /** @deprecated use `Getv1ApisNamespaceRequest$Outbound` instead. */
  export type Outbound = Getv1ApisNamespaceRequest$Outbound;
}

export function getv1ApisNamespaceRequestToJSON(
  getv1ApisNamespaceRequest: Getv1ApisNamespaceRequest,
): string {
  return JSON.stringify(
    Getv1ApisNamespaceRequest$outboundSchema.parse(getv1ApisNamespaceRequest),
  );
}

export function getv1ApisNamespaceRequestFromJSON(
  jsonString: string,
): SafeParseResult<Getv1ApisNamespaceRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Getv1ApisNamespaceRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Getv1ApisNamespaceRequest' from JSON`,
  );
}
