/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Getv1LoginPortalsSlugRequest = {
  slug: string;
};

/**
 * Default Response
 */
export type Getv1LoginPortalsSlugResponseBody = {
  uid: string;
  title: string;
  slug: string;
  email: components.LoginPortalEmail;
  page: components.LoginPortalPage;
};

/** @internal */
export const Getv1LoginPortalsSlugRequest$inboundSchema: z.ZodType<
  Getv1LoginPortalsSlugRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  slug: z.string(),
});

/** @internal */
export type Getv1LoginPortalsSlugRequest$Outbound = {
  slug: string;
};

/** @internal */
export const Getv1LoginPortalsSlugRequest$outboundSchema: z.ZodType<
  Getv1LoginPortalsSlugRequest$Outbound,
  z.ZodTypeDef,
  Getv1LoginPortalsSlugRequest
> = z.object({
  slug: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Getv1LoginPortalsSlugRequest$ {
  /** @deprecated use `Getv1LoginPortalsSlugRequest$inboundSchema` instead. */
  export const inboundSchema = Getv1LoginPortalsSlugRequest$inboundSchema;
  /** @deprecated use `Getv1LoginPortalsSlugRequest$outboundSchema` instead. */
  export const outboundSchema = Getv1LoginPortalsSlugRequest$outboundSchema;
  /** @deprecated use `Getv1LoginPortalsSlugRequest$Outbound` instead. */
  export type Outbound = Getv1LoginPortalsSlugRequest$Outbound;
}

export function getv1LoginPortalsSlugRequestToJSON(
  getv1LoginPortalsSlugRequest: Getv1LoginPortalsSlugRequest,
): string {
  return JSON.stringify(
    Getv1LoginPortalsSlugRequest$outboundSchema.parse(
      getv1LoginPortalsSlugRequest,
    ),
  );
}

export function getv1LoginPortalsSlugRequestFromJSON(
  jsonString: string,
): SafeParseResult<Getv1LoginPortalsSlugRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Getv1LoginPortalsSlugRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Getv1LoginPortalsSlugRequest' from JSON`,
  );
}

/** @internal */
export const Getv1LoginPortalsSlugResponseBody$inboundSchema: z.ZodType<
  Getv1LoginPortalsSlugResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  uid: z.string(),
  title: z.string(),
  slug: z.string(),
  email: components.LoginPortalEmail$inboundSchema,
  page: components.LoginPortalPage$inboundSchema,
});

/** @internal */
export type Getv1LoginPortalsSlugResponseBody$Outbound = {
  uid: string;
  title: string;
  slug: string;
  email: components.LoginPortalEmail$Outbound;
  page: components.LoginPortalPage$Outbound;
};

/** @internal */
export const Getv1LoginPortalsSlugResponseBody$outboundSchema: z.ZodType<
  Getv1LoginPortalsSlugResponseBody$Outbound,
  z.ZodTypeDef,
  Getv1LoginPortalsSlugResponseBody
> = z.object({
  uid: z.string(),
  title: z.string(),
  slug: z.string(),
  email: components.LoginPortalEmail$outboundSchema,
  page: components.LoginPortalPage$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Getv1LoginPortalsSlugResponseBody$ {
  /** @deprecated use `Getv1LoginPortalsSlugResponseBody$inboundSchema` instead. */
  export const inboundSchema = Getv1LoginPortalsSlugResponseBody$inboundSchema;
  /** @deprecated use `Getv1LoginPortalsSlugResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    Getv1LoginPortalsSlugResponseBody$outboundSchema;
  /** @deprecated use `Getv1LoginPortalsSlugResponseBody$Outbound` instead. */
  export type Outbound = Getv1LoginPortalsSlugResponseBody$Outbound;
}

export function getv1LoginPortalsSlugResponseBodyToJSON(
  getv1LoginPortalsSlugResponseBody: Getv1LoginPortalsSlugResponseBody,
): string {
  return JSON.stringify(
    Getv1LoginPortalsSlugResponseBody$outboundSchema.parse(
      getv1LoginPortalsSlugResponseBody,
    ),
  );
}

export function getv1LoginPortalsSlugResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<Getv1LoginPortalsSlugResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Getv1LoginPortalsSlugResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Getv1LoginPortalsSlugResponseBody' from JSON`,
  );
}
