/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListTeamsResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Default Response
   */
  teams?: Array<components.Team> | undefined;
};

/** @internal */
export const ListTeamsResponse$inboundSchema: z.ZodType<
  ListTeamsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  teams: z.array(components.Team$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
  });
});

/** @internal */
export type ListTeamsResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  teams?: Array<components.Team$Outbound> | undefined;
};

/** @internal */
export const ListTeamsResponse$outboundSchema: z.ZodType<
  ListTeamsResponse$Outbound,
  z.ZodTypeDef,
  ListTeamsResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  teams: z.array(components.Team$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListTeamsResponse$ {
  /** @deprecated use `ListTeamsResponse$inboundSchema` instead. */
  export const inboundSchema = ListTeamsResponse$inboundSchema;
  /** @deprecated use `ListTeamsResponse$outboundSchema` instead. */
  export const outboundSchema = ListTeamsResponse$outboundSchema;
  /** @deprecated use `ListTeamsResponse$Outbound` instead. */
  export type Outbound = ListTeamsResponse$Outbound;
}

export function listTeamsResponseToJSON(
  listTeamsResponse: ListTeamsResponse,
): string {
  return JSON.stringify(
    ListTeamsResponse$outboundSchema.parse(listTeamsResponse),
  );
}

export function listTeamsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListTeamsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListTeamsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListTeamsResponse' from JSON`,
  );
}
