/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListGuidesResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Default Response
   */
  githubProjects?: Array<components.GithubProject> | undefined;
};

/** @internal */
export const ListGuidesResponse$inboundSchema: z.ZodType<
  ListGuidesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  "github-projects": z.array(components.GithubProject$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "github-projects": "githubProjects",
  });
});

/** @internal */
export type ListGuidesResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  "github-projects"?: Array<components.GithubProject$Outbound> | undefined;
};

/** @internal */
export const ListGuidesResponse$outboundSchema: z.ZodType<
  ListGuidesResponse$Outbound,
  z.ZodTypeDef,
  ListGuidesResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  githubProjects: z.array(components.GithubProject$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    githubProjects: "github-projects",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListGuidesResponse$ {
  /** @deprecated use `ListGuidesResponse$inboundSchema` instead. */
  export const inboundSchema = ListGuidesResponse$inboundSchema;
  /** @deprecated use `ListGuidesResponse$outboundSchema` instead. */
  export const outboundSchema = ListGuidesResponse$outboundSchema;
  /** @deprecated use `ListGuidesResponse$Outbound` instead. */
  export type Outbound = ListGuidesResponse$Outbound;
}

export function listGuidesResponseToJSON(
  listGuidesResponse: ListGuidesResponse,
): string {
  return JSON.stringify(
    ListGuidesResponse$outboundSchema.parse(listGuidesResponse),
  );
}

export function listGuidesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListGuidesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListGuidesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListGuidesResponse' from JSON`,
  );
}
