/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListAllApiDocumentsResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Default Response
   */
  apiDocuments?: Array<components.ApiDocument> | undefined;
};

/** @internal */
export const ListAllApiDocumentsResponse$inboundSchema: z.ZodType<
  ListAllApiDocumentsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  "api-documents": z.array(components.ApiDocument$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "api-documents": "apiDocuments",
  });
});

/** @internal */
export type ListAllApiDocumentsResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  "api-documents"?: Array<components.ApiDocument$Outbound> | undefined;
};

/** @internal */
export const ListAllApiDocumentsResponse$outboundSchema: z.ZodType<
  ListAllApiDocumentsResponse$Outbound,
  z.ZodTypeDef,
  ListAllApiDocumentsResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  apiDocuments: z.array(components.ApiDocument$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    apiDocuments: "api-documents",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListAllApiDocumentsResponse$ {
  /** @deprecated use `ListAllApiDocumentsResponse$inboundSchema` instead. */
  export const inboundSchema = ListAllApiDocumentsResponse$inboundSchema;
  /** @deprecated use `ListAllApiDocumentsResponse$outboundSchema` instead. */
  export const outboundSchema = ListAllApiDocumentsResponse$outboundSchema;
  /** @deprecated use `ListAllApiDocumentsResponse$Outbound` instead. */
  export type Outbound = ListAllApiDocumentsResponse$Outbound;
}

export function listAllApiDocumentsResponseToJSON(
  listAllApiDocumentsResponse: ListAllApiDocumentsResponse,
): string {
  return JSON.stringify(
    ListAllApiDocumentsResponse$outboundSchema.parse(
      listAllApiDocumentsResponse,
    ),
  );
}

export function listAllApiDocumentsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListAllApiDocumentsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListAllApiDocumentsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAllApiDocumentsResponse' from JSON`,
  );
}
