/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListLoginPortalsResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Default Response
   */
  loginPortals?: Array<components.LoginPortal> | undefined;
};

/** @internal */
export const ListLoginPortalsResponse$inboundSchema: z.ZodType<
  ListLoginPortalsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  "login-portals": z.array(components.LoginPortal$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "login-portals": "loginPortals",
  });
});

/** @internal */
export type ListLoginPortalsResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  "login-portals"?: Array<components.LoginPortal$Outbound> | undefined;
};

/** @internal */
export const ListLoginPortalsResponse$outboundSchema: z.ZodType<
  ListLoginPortalsResponse$Outbound,
  z.ZodTypeDef,
  ListLoginPortalsResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  loginPortals: z.array(components.LoginPortal$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    loginPortals: "login-portals",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListLoginPortalsResponse$ {
  /** @deprecated use `ListLoginPortalsResponse$inboundSchema` instead. */
  export const inboundSchema = ListLoginPortalsResponse$inboundSchema;
  /** @deprecated use `ListLoginPortalsResponse$outboundSchema` instead. */
  export const outboundSchema = ListLoginPortalsResponse$outboundSchema;
  /** @deprecated use `ListLoginPortalsResponse$Outbound` instead. */
  export type Outbound = ListLoginPortalsResponse$Outbound;
}

export function listLoginPortalsResponseToJSON(
  listLoginPortalsResponse: ListLoginPortalsResponse,
): string {
  return JSON.stringify(
    ListLoginPortalsResponse$outboundSchema.parse(listLoginPortalsResponse),
  );
}

export function listLoginPortalsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListLoginPortalsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListLoginPortalsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListLoginPortalsResponse' from JSON`,
  );
}
