/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListThemesResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Default Response
   */
  themes?: Array<components.Theme> | undefined;
};

/** @internal */
export const ListThemesResponse$inboundSchema: z.ZodType<
  ListThemesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  themes: z.array(components.Theme$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
  });
});

/** @internal */
export type ListThemesResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  themes?: Array<components.Theme$Outbound> | undefined;
};

/** @internal */
export const ListThemesResponse$outboundSchema: z.ZodType<
  ListThemesResponse$Outbound,
  z.ZodTypeDef,
  ListThemesResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  themes: z.array(components.Theme$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListThemesResponse$ {
  /** @deprecated use `ListThemesResponse$inboundSchema` instead. */
  export const inboundSchema = ListThemesResponse$inboundSchema;
  /** @deprecated use `ListThemesResponse$outboundSchema` instead. */
  export const outboundSchema = ListThemesResponse$outboundSchema;
  /** @deprecated use `ListThemesResponse$Outbound` instead. */
  export type Outbound = ListThemesResponse$Outbound;
}

export function listThemesResponseToJSON(
  listThemesResponse: ListThemesResponse,
): string {
  return JSON.stringify(
    ListThemesResponse$outboundSchema.parse(listThemesResponse),
  );
}

export function listThemesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListThemesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListThemesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListThemesResponse' from JSON`,
  );
}
