/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListRulesetsRequest = {
  namespace: string;
};

/** @internal */
export const ListRulesetsRequest$inboundSchema: z.ZodType<
  ListRulesetsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  namespace: z.string(),
});

/** @internal */
export type ListRulesetsRequest$Outbound = {
  namespace: string;
};

/** @internal */
export const ListRulesetsRequest$outboundSchema: z.ZodType<
  ListRulesetsRequest$Outbound,
  z.ZodTypeDef,
  ListRulesetsRequest
> = z.object({
  namespace: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListRulesetsRequest$ {
  /** @deprecated use `ListRulesetsRequest$inboundSchema` instead. */
  export const inboundSchema = ListRulesetsRequest$inboundSchema;
  /** @deprecated use `ListRulesetsRequest$outboundSchema` instead. */
  export const outboundSchema = ListRulesetsRequest$outboundSchema;
  /** @deprecated use `ListRulesetsRequest$Outbound` instead. */
  export type Outbound = ListRulesetsRequest$Outbound;
}

export function listRulesetsRequestToJSON(
  listRulesetsRequest: ListRulesetsRequest,
): string {
  return JSON.stringify(
    ListRulesetsRequest$outboundSchema.parse(listRulesetsRequest),
  );
}

export function listRulesetsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListRulesetsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListRulesetsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListRulesetsRequest' from JSON`,
  );
}
