/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Postv1GuidesSlugPublishRequest = {
  slug: string;
};

/**
 * Default Response
 */
export type Postv1GuidesSlugPublishResponseBody = {
  publishUid: string;
};

/** @internal */
export const Postv1GuidesSlugPublishRequest$inboundSchema: z.ZodType<
  Postv1GuidesSlugPublishRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  slug: z.string(),
});

/** @internal */
export type Postv1GuidesSlugPublishRequest$Outbound = {
  slug: string;
};

/** @internal */
export const Postv1GuidesSlugPublishRequest$outboundSchema: z.ZodType<
  Postv1GuidesSlugPublishRequest$Outbound,
  z.ZodTypeDef,
  Postv1GuidesSlugPublishRequest
> = z.object({
  slug: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Postv1GuidesSlugPublishRequest$ {
  /** @deprecated use `Postv1GuidesSlugPublishRequest$inboundSchema` instead. */
  export const inboundSchema = Postv1GuidesSlugPublishRequest$inboundSchema;
  /** @deprecated use `Postv1GuidesSlugPublishRequest$outboundSchema` instead. */
  export const outboundSchema = Postv1GuidesSlugPublishRequest$outboundSchema;
  /** @deprecated use `Postv1GuidesSlugPublishRequest$Outbound` instead. */
  export type Outbound = Postv1GuidesSlugPublishRequest$Outbound;
}

export function postv1GuidesSlugPublishRequestToJSON(
  postv1GuidesSlugPublishRequest: Postv1GuidesSlugPublishRequest,
): string {
  return JSON.stringify(
    Postv1GuidesSlugPublishRequest$outboundSchema.parse(
      postv1GuidesSlugPublishRequest,
    ),
  );
}

export function postv1GuidesSlugPublishRequestFromJSON(
  jsonString: string,
): SafeParseResult<Postv1GuidesSlugPublishRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Postv1GuidesSlugPublishRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Postv1GuidesSlugPublishRequest' from JSON`,
  );
}

/** @internal */
export const Postv1GuidesSlugPublishResponseBody$inboundSchema: z.ZodType<
  Postv1GuidesSlugPublishResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  publishUid: z.string(),
});

/** @internal */
export type Postv1GuidesSlugPublishResponseBody$Outbound = {
  publishUid: string;
};

/** @internal */
export const Postv1GuidesSlugPublishResponseBody$outboundSchema: z.ZodType<
  Postv1GuidesSlugPublishResponseBody$Outbound,
  z.ZodTypeDef,
  Postv1GuidesSlugPublishResponseBody
> = z.object({
  publishUid: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Postv1GuidesSlugPublishResponseBody$ {
  /** @deprecated use `Postv1GuidesSlugPublishResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    Postv1GuidesSlugPublishResponseBody$inboundSchema;
  /** @deprecated use `Postv1GuidesSlugPublishResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    Postv1GuidesSlugPublishResponseBody$outboundSchema;
  /** @deprecated use `Postv1GuidesSlugPublishResponseBody$Outbound` instead. */
  export type Outbound = Postv1GuidesSlugPublishResponseBody$Outbound;
}

export function postv1GuidesSlugPublishResponseBodyToJSON(
  postv1GuidesSlugPublishResponseBody: Postv1GuidesSlugPublishResponseBody,
): string {
  return JSON.stringify(
    Postv1GuidesSlugPublishResponseBody$outboundSchema.parse(
      postv1GuidesSlugPublishResponseBody,
    ),
  );
}

export function postv1GuidesSlugPublishResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<Postv1GuidesSlugPublishResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      Postv1GuidesSlugPublishResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Postv1GuidesSlugPublishResponseBody' from JSON`,
  );
}
