/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Postv1SchemasNamespaceSlugAccessGroupRequest = {
  namespace: string;
  slug: string;
  accessGroup: components.AccessGroup;
};

/** @internal */
export const Postv1SchemasNamespaceSlugAccessGroupRequest$inboundSchema:
  z.ZodType<
    Postv1SchemasNamespaceSlugAccessGroupRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    namespace: z.string(),
    slug: z.string(),
    "access-group": components.AccessGroup$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "access-group": "accessGroup",
    });
  });

/** @internal */
export type Postv1SchemasNamespaceSlugAccessGroupRequest$Outbound = {
  namespace: string;
  slug: string;
  "access-group": components.AccessGroup$Outbound;
};

/** @internal */
export const Postv1SchemasNamespaceSlugAccessGroupRequest$outboundSchema:
  z.ZodType<
    Postv1SchemasNamespaceSlugAccessGroupRequest$Outbound,
    z.ZodTypeDef,
    Postv1SchemasNamespaceSlugAccessGroupRequest
  > = z.object({
    namespace: z.string(),
    slug: z.string(),
    accessGroup: components.AccessGroup$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      accessGroup: "access-group",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Postv1SchemasNamespaceSlugAccessGroupRequest$ {
  /** @deprecated use `Postv1SchemasNamespaceSlugAccessGroupRequest$inboundSchema` instead. */
  export const inboundSchema =
    Postv1SchemasNamespaceSlugAccessGroupRequest$inboundSchema;
  /** @deprecated use `Postv1SchemasNamespaceSlugAccessGroupRequest$outboundSchema` instead. */
  export const outboundSchema =
    Postv1SchemasNamespaceSlugAccessGroupRequest$outboundSchema;
  /** @deprecated use `Postv1SchemasNamespaceSlugAccessGroupRequest$Outbound` instead. */
  export type Outbound = Postv1SchemasNamespaceSlugAccessGroupRequest$Outbound;
}

export function postv1SchemasNamespaceSlugAccessGroupRequestToJSON(
  postv1SchemasNamespaceSlugAccessGroupRequest:
    Postv1SchemasNamespaceSlugAccessGroupRequest,
): string {
  return JSON.stringify(
    Postv1SchemasNamespaceSlugAccessGroupRequest$outboundSchema.parse(
      postv1SchemasNamespaceSlugAccessGroupRequest,
    ),
  );
}

export function postv1SchemasNamespaceSlugAccessGroupRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  Postv1SchemasNamespaceSlugAccessGroupRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      Postv1SchemasNamespaceSlugAccessGroupRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'Postv1SchemasNamespaceSlugAccessGroupRequest' from JSON`,
  );
}
