/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Postv1ApisNamespaceSlugAccessGroupRequest = {
  namespace: string;
  slug: string;
  accessGroup: components.AccessGroup;
};

/** @internal */
export const Postv1ApisNamespaceSlugAccessGroupRequest$inboundSchema: z.ZodType<
  Postv1ApisNamespaceSlugAccessGroupRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  namespace: z.string(),
  slug: z.string(),
  "access-group": components.AccessGroup$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "access-group": "accessGroup",
  });
});

/** @internal */
export type Postv1ApisNamespaceSlugAccessGroupRequest$Outbound = {
  namespace: string;
  slug: string;
  "access-group": components.AccessGroup$Outbound;
};

/** @internal */
export const Postv1ApisNamespaceSlugAccessGroupRequest$outboundSchema:
  z.ZodType<
    Postv1ApisNamespaceSlugAccessGroupRequest$Outbound,
    z.ZodTypeDef,
    Postv1ApisNamespaceSlugAccessGroupRequest
  > = z.object({
    namespace: z.string(),
    slug: z.string(),
    accessGroup: components.AccessGroup$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      accessGroup: "access-group",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Postv1ApisNamespaceSlugAccessGroupRequest$ {
  /** @deprecated use `Postv1ApisNamespaceSlugAccessGroupRequest$inboundSchema` instead. */
  export const inboundSchema =
    Postv1ApisNamespaceSlugAccessGroupRequest$inboundSchema;
  /** @deprecated use `Postv1ApisNamespaceSlugAccessGroupRequest$outboundSchema` instead. */
  export const outboundSchema =
    Postv1ApisNamespaceSlugAccessGroupRequest$outboundSchema;
  /** @deprecated use `Postv1ApisNamespaceSlugAccessGroupRequest$Outbound` instead. */
  export type Outbound = Postv1ApisNamespaceSlugAccessGroupRequest$Outbound;
}

export function postv1ApisNamespaceSlugAccessGroupRequestToJSON(
  postv1ApisNamespaceSlugAccessGroupRequest:
    Postv1ApisNamespaceSlugAccessGroupRequest,
): string {
  return JSON.stringify(
    Postv1ApisNamespaceSlugAccessGroupRequest$outboundSchema.parse(
      postv1ApisNamespaceSlugAccessGroupRequest,
    ),
  );
}

export function postv1ApisNamespaceSlugAccessGroupRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  Postv1ApisNamespaceSlugAccessGroupRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      Postv1ApisNamespaceSlugAccessGroupRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'Postv1ApisNamespaceSlugAccessGroupRequest' from JSON`,
  );
}
