/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PublishGuideRequest = {
  slug: string;
};

/**
 * Default Response
 */
export type PublishGuideResponseBody = {
  publishUid: string;
};

/** @internal */
export const PublishGuideRequest$inboundSchema: z.ZodType<
  PublishGuideRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  slug: z.string(),
});

/** @internal */
export type PublishGuideRequest$Outbound = {
  slug: string;
};

/** @internal */
export const PublishGuideRequest$outboundSchema: z.ZodType<
  PublishGuideRequest$Outbound,
  z.ZodTypeDef,
  PublishGuideRequest
> = z.object({
  slug: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PublishGuideRequest$ {
  /** @deprecated use `PublishGuideRequest$inboundSchema` instead. */
  export const inboundSchema = PublishGuideRequest$inboundSchema;
  /** @deprecated use `PublishGuideRequest$outboundSchema` instead. */
  export const outboundSchema = PublishGuideRequest$outboundSchema;
  /** @deprecated use `PublishGuideRequest$Outbound` instead. */
  export type Outbound = PublishGuideRequest$Outbound;
}

export function publishGuideRequestToJSON(
  publishGuideRequest: PublishGuideRequest,
): string {
  return JSON.stringify(
    PublishGuideRequest$outboundSchema.parse(publishGuideRequest),
  );
}

export function publishGuideRequestFromJSON(
  jsonString: string,
): SafeParseResult<PublishGuideRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PublishGuideRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PublishGuideRequest' from JSON`,
  );
}

/** @internal */
export const PublishGuideResponseBody$inboundSchema: z.ZodType<
  PublishGuideResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  publishUid: z.string(),
});

/** @internal */
export type PublishGuideResponseBody$Outbound = {
  publishUid: string;
};

/** @internal */
export const PublishGuideResponseBody$outboundSchema: z.ZodType<
  PublishGuideResponseBody$Outbound,
  z.ZodTypeDef,
  PublishGuideResponseBody
> = z.object({
  publishUid: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PublishGuideResponseBody$ {
  /** @deprecated use `PublishGuideResponseBody$inboundSchema` instead. */
  export const inboundSchema = PublishGuideResponseBody$inboundSchema;
  /** @deprecated use `PublishGuideResponseBody$outboundSchema` instead. */
  export const outboundSchema = PublishGuideResponseBody$outboundSchema;
  /** @deprecated use `PublishGuideResponseBody$Outbound` instead. */
  export type Outbound = PublishGuideResponseBody$Outbound;
}

export function publishGuideResponseBodyToJSON(
  publishGuideResponseBody: PublishGuideResponseBody,
): string {
  return JSON.stringify(
    PublishGuideResponseBody$outboundSchema.parse(publishGuideResponseBody),
  );
}

export function publishGuideResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PublishGuideResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PublishGuideResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PublishGuideResponseBody' from JSON`,
  );
}
