/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RemoveApiDocumentAccessGroupRequest = {
  namespace: string;
  slug: string;
  accessGroup: components.AccessGroup;
};

/** @internal */
export const RemoveApiDocumentAccessGroupRequest$inboundSchema: z.ZodType<
  RemoveApiDocumentAccessGroupRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  namespace: z.string(),
  slug: z.string(),
  "access-group": components.AccessGroup$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "access-group": "accessGroup",
  });
});

/** @internal */
export type RemoveApiDocumentAccessGroupRequest$Outbound = {
  namespace: string;
  slug: string;
  "access-group": components.AccessGroup$Outbound;
};

/** @internal */
export const RemoveApiDocumentAccessGroupRequest$outboundSchema: z.ZodType<
  RemoveApiDocumentAccessGroupRequest$Outbound,
  z.ZodTypeDef,
  RemoveApiDocumentAccessGroupRequest
> = z.object({
  namespace: z.string(),
  slug: z.string(),
  accessGroup: components.AccessGroup$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    accessGroup: "access-group",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RemoveApiDocumentAccessGroupRequest$ {
  /** @deprecated use `RemoveApiDocumentAccessGroupRequest$inboundSchema` instead. */
  export const inboundSchema =
    RemoveApiDocumentAccessGroupRequest$inboundSchema;
  /** @deprecated use `RemoveApiDocumentAccessGroupRequest$outboundSchema` instead. */
  export const outboundSchema =
    RemoveApiDocumentAccessGroupRequest$outboundSchema;
  /** @deprecated use `RemoveApiDocumentAccessGroupRequest$Outbound` instead. */
  export type Outbound = RemoveApiDocumentAccessGroupRequest$Outbound;
}

export function removeApiDocumentAccessGroupRequestToJSON(
  removeApiDocumentAccessGroupRequest: RemoveApiDocumentAccessGroupRequest,
): string {
  return JSON.stringify(
    RemoveApiDocumentAccessGroupRequest$outboundSchema.parse(
      removeApiDocumentAccessGroupRequest,
    ),
  );
}

export function removeApiDocumentAccessGroupRequestFromJSON(
  jsonString: string,
): SafeParseResult<RemoveApiDocumentAccessGroupRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      RemoveApiDocumentAccessGroupRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RemoveApiDocumentAccessGroupRequest' from JSON`,
  );
}
