/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RemoveSchemaAccessGroupRequest = {
  namespace: string;
  slug: string;
  accessGroup: components.AccessGroup;
};

export type RemoveSchemaAccessGroupResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Default Response
   */
  any?: any | null | undefined;
};

/** @internal */
export const RemoveSchemaAccessGroupRequest$inboundSchema: z.ZodType<
  RemoveSchemaAccessGroupRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  namespace: z.string(),
  slug: z.string(),
  "access-group": components.AccessGroup$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "access-group": "accessGroup",
  });
});

/** @internal */
export type RemoveSchemaAccessGroupRequest$Outbound = {
  namespace: string;
  slug: string;
  "access-group": components.AccessGroup$Outbound;
};

/** @internal */
export const RemoveSchemaAccessGroupRequest$outboundSchema: z.ZodType<
  RemoveSchemaAccessGroupRequest$Outbound,
  z.ZodTypeDef,
  RemoveSchemaAccessGroupRequest
> = z.object({
  namespace: z.string(),
  slug: z.string(),
  accessGroup: components.AccessGroup$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    accessGroup: "access-group",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RemoveSchemaAccessGroupRequest$ {
  /** @deprecated use `RemoveSchemaAccessGroupRequest$inboundSchema` instead. */
  export const inboundSchema = RemoveSchemaAccessGroupRequest$inboundSchema;
  /** @deprecated use `RemoveSchemaAccessGroupRequest$outboundSchema` instead. */
  export const outboundSchema = RemoveSchemaAccessGroupRequest$outboundSchema;
  /** @deprecated use `RemoveSchemaAccessGroupRequest$Outbound` instead. */
  export type Outbound = RemoveSchemaAccessGroupRequest$Outbound;
}

export function removeSchemaAccessGroupRequestToJSON(
  removeSchemaAccessGroupRequest: RemoveSchemaAccessGroupRequest,
): string {
  return JSON.stringify(
    RemoveSchemaAccessGroupRequest$outboundSchema.parse(
      removeSchemaAccessGroupRequest,
    ),
  );
}

export function removeSchemaAccessGroupRequestFromJSON(
  jsonString: string,
): SafeParseResult<RemoveSchemaAccessGroupRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RemoveSchemaAccessGroupRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RemoveSchemaAccessGroupRequest' from JSON`,
  );
}

/** @internal */
export const RemoveSchemaAccessGroupResponse$inboundSchema: z.ZodType<
  RemoveSchemaAccessGroupResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  any: z.nullable(z.any()).optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
  });
});

/** @internal */
export type RemoveSchemaAccessGroupResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  any?: any | null | undefined;
};

/** @internal */
export const RemoveSchemaAccessGroupResponse$outboundSchema: z.ZodType<
  RemoveSchemaAccessGroupResponse$Outbound,
  z.ZodTypeDef,
  RemoveSchemaAccessGroupResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  any: z.nullable(z.any()).optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RemoveSchemaAccessGroupResponse$ {
  /** @deprecated use `RemoveSchemaAccessGroupResponse$inboundSchema` instead. */
  export const inboundSchema = RemoveSchemaAccessGroupResponse$inboundSchema;
  /** @deprecated use `RemoveSchemaAccessGroupResponse$outboundSchema` instead. */
  export const outboundSchema = RemoveSchemaAccessGroupResponse$outboundSchema;
  /** @deprecated use `RemoveSchemaAccessGroupResponse$Outbound` instead. */
  export type Outbound = RemoveSchemaAccessGroupResponse$Outbound;
}

export function removeSchemaAccessGroupResponseToJSON(
  removeSchemaAccessGroupResponse: RemoveSchemaAccessGroupResponse,
): string {
  return JSON.stringify(
    RemoveSchemaAccessGroupResponse$outboundSchema.parse(
      removeSchemaAccessGroupResponse,
    ),
  );
}

export function removeSchemaAccessGroupResponseFromJSON(
  jsonString: string,
): SafeParseResult<RemoveSchemaAccessGroupResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RemoveSchemaAccessGroupResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RemoveSchemaAccessGroupResponse' from JSON`,
  );
}
