/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RemoveRulesetAccessGroupRequest = {
  namespace: string;
  slug: string;
  accessGroup: components.AccessGroup;
};

/** @internal */
export const RemoveRulesetAccessGroupRequest$inboundSchema: z.ZodType<
  RemoveRulesetAccessGroupRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  namespace: z.string(),
  slug: z.string(),
  "access-group": components.AccessGroup$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "access-group": "accessGroup",
  });
});

/** @internal */
export type RemoveRulesetAccessGroupRequest$Outbound = {
  namespace: string;
  slug: string;
  "access-group": components.AccessGroup$Outbound;
};

/** @internal */
export const RemoveRulesetAccessGroupRequest$outboundSchema: z.ZodType<
  RemoveRulesetAccessGroupRequest$Outbound,
  z.ZodTypeDef,
  RemoveRulesetAccessGroupRequest
> = z.object({
  namespace: z.string(),
  slug: z.string(),
  accessGroup: components.AccessGroup$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    accessGroup: "access-group",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RemoveRulesetAccessGroupRequest$ {
  /** @deprecated use `RemoveRulesetAccessGroupRequest$inboundSchema` instead. */
  export const inboundSchema = RemoveRulesetAccessGroupRequest$inboundSchema;
  /** @deprecated use `RemoveRulesetAccessGroupRequest$outboundSchema` instead. */
  export const outboundSchema = RemoveRulesetAccessGroupRequest$outboundSchema;
  /** @deprecated use `RemoveRulesetAccessGroupRequest$Outbound` instead. */
  export type Outbound = RemoveRulesetAccessGroupRequest$Outbound;
}

export function removeRulesetAccessGroupRequestToJSON(
  removeRulesetAccessGroupRequest: RemoveRulesetAccessGroupRequest,
): string {
  return JSON.stringify(
    RemoveRulesetAccessGroupRequest$outboundSchema.parse(
      removeRulesetAccessGroupRequest,
    ),
  );
}

export function removeRulesetAccessGroupRequestFromJSON(
  jsonString: string,
): SafeParseResult<RemoveRulesetAccessGroupRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RemoveRulesetAccessGroupRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RemoveRulesetAccessGroupRequest' from JSON`,
  );
}
