/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ReplaceThemeDocumentRequestBody = {
  document: string;
};

export type ReplaceThemeDocumentRequest = {
  slug: string;
  requestBody: ReplaceThemeDocumentRequestBody;
};

export type ReplaceThemeDocumentResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Default Response
   */
  any?: any | null | undefined;
};

/** @internal */
export const ReplaceThemeDocumentRequestBody$inboundSchema: z.ZodType<
  ReplaceThemeDocumentRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  document: z.string(),
});

/** @internal */
export type ReplaceThemeDocumentRequestBody$Outbound = {
  document: string;
};

/** @internal */
export const ReplaceThemeDocumentRequestBody$outboundSchema: z.ZodType<
  ReplaceThemeDocumentRequestBody$Outbound,
  z.ZodTypeDef,
  ReplaceThemeDocumentRequestBody
> = z.object({
  document: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ReplaceThemeDocumentRequestBody$ {
  /** @deprecated use `ReplaceThemeDocumentRequestBody$inboundSchema` instead. */
  export const inboundSchema = ReplaceThemeDocumentRequestBody$inboundSchema;
  /** @deprecated use `ReplaceThemeDocumentRequestBody$outboundSchema` instead. */
  export const outboundSchema = ReplaceThemeDocumentRequestBody$outboundSchema;
  /** @deprecated use `ReplaceThemeDocumentRequestBody$Outbound` instead. */
  export type Outbound = ReplaceThemeDocumentRequestBody$Outbound;
}

export function replaceThemeDocumentRequestBodyToJSON(
  replaceThemeDocumentRequestBody: ReplaceThemeDocumentRequestBody,
): string {
  return JSON.stringify(
    ReplaceThemeDocumentRequestBody$outboundSchema.parse(
      replaceThemeDocumentRequestBody,
    ),
  );
}

export function replaceThemeDocumentRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<ReplaceThemeDocumentRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReplaceThemeDocumentRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReplaceThemeDocumentRequestBody' from JSON`,
  );
}

/** @internal */
export const ReplaceThemeDocumentRequest$inboundSchema: z.ZodType<
  ReplaceThemeDocumentRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  slug: z.string(),
  RequestBody: z.lazy(() => ReplaceThemeDocumentRequestBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type ReplaceThemeDocumentRequest$Outbound = {
  slug: string;
  RequestBody: ReplaceThemeDocumentRequestBody$Outbound;
};

/** @internal */
export const ReplaceThemeDocumentRequest$outboundSchema: z.ZodType<
  ReplaceThemeDocumentRequest$Outbound,
  z.ZodTypeDef,
  ReplaceThemeDocumentRequest
> = z.object({
  slug: z.string(),
  requestBody: z.lazy(() => ReplaceThemeDocumentRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ReplaceThemeDocumentRequest$ {
  /** @deprecated use `ReplaceThemeDocumentRequest$inboundSchema` instead. */
  export const inboundSchema = ReplaceThemeDocumentRequest$inboundSchema;
  /** @deprecated use `ReplaceThemeDocumentRequest$outboundSchema` instead. */
  export const outboundSchema = ReplaceThemeDocumentRequest$outboundSchema;
  /** @deprecated use `ReplaceThemeDocumentRequest$Outbound` instead. */
  export type Outbound = ReplaceThemeDocumentRequest$Outbound;
}

export function replaceThemeDocumentRequestToJSON(
  replaceThemeDocumentRequest: ReplaceThemeDocumentRequest,
): string {
  return JSON.stringify(
    ReplaceThemeDocumentRequest$outboundSchema.parse(
      replaceThemeDocumentRequest,
    ),
  );
}

export function replaceThemeDocumentRequestFromJSON(
  jsonString: string,
): SafeParseResult<ReplaceThemeDocumentRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReplaceThemeDocumentRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReplaceThemeDocumentRequest' from JSON`,
  );
}

/** @internal */
export const ReplaceThemeDocumentResponse$inboundSchema: z.ZodType<
  ReplaceThemeDocumentResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  any: z.nullable(z.any()).optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
  });
});

/** @internal */
export type ReplaceThemeDocumentResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  any?: any | null | undefined;
};

/** @internal */
export const ReplaceThemeDocumentResponse$outboundSchema: z.ZodType<
  ReplaceThemeDocumentResponse$Outbound,
  z.ZodTypeDef,
  ReplaceThemeDocumentResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  any: z.nullable(z.any()).optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ReplaceThemeDocumentResponse$ {
  /** @deprecated use `ReplaceThemeDocumentResponse$inboundSchema` instead. */
  export const inboundSchema = ReplaceThemeDocumentResponse$inboundSchema;
  /** @deprecated use `ReplaceThemeDocumentResponse$outboundSchema` instead. */
  export const outboundSchema = ReplaceThemeDocumentResponse$outboundSchema;
  /** @deprecated use `ReplaceThemeDocumentResponse$Outbound` instead. */
  export type Outbound = ReplaceThemeDocumentResponse$Outbound;
}

export function replaceThemeDocumentResponseToJSON(
  replaceThemeDocumentResponse: ReplaceThemeDocumentResponse,
): string {
  return JSON.stringify(
    ReplaceThemeDocumentResponse$outboundSchema.parse(
      replaceThemeDocumentResponse,
    ),
  );
}

export function replaceThemeDocumentResponseFromJSON(
  jsonString: string,
): SafeParseResult<ReplaceThemeDocumentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReplaceThemeDocumentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReplaceThemeDocumentResponse' from JSON`,
  );
}
