/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateRulesetRequestBody = {
  namespace?: string | undefined;
  slug?: string | undefined;
  title?: string | undefined;
  description?: string | undefined;
  isPrivate?: boolean | undefined;
};

export type UpdateRulesetRequest = {
  namespace: string;
  slug: string;
  requestBody: UpdateRulesetRequestBody;
};

export type UpdateRulesetResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Default Response
   */
  any?: any | null | undefined;
};

/** @internal */
export const UpdateRulesetRequestBody$inboundSchema: z.ZodType<
  UpdateRulesetRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  namespace: z.string().optional(),
  slug: z.string().optional(),
  title: z.string().optional(),
  description: z.string().optional(),
  isPrivate: z.boolean().optional(),
});

/** @internal */
export type UpdateRulesetRequestBody$Outbound = {
  namespace?: string | undefined;
  slug?: string | undefined;
  title?: string | undefined;
  description?: string | undefined;
  isPrivate?: boolean | undefined;
};

/** @internal */
export const UpdateRulesetRequestBody$outboundSchema: z.ZodType<
  UpdateRulesetRequestBody$Outbound,
  z.ZodTypeDef,
  UpdateRulesetRequestBody
> = z.object({
  namespace: z.string().optional(),
  slug: z.string().optional(),
  title: z.string().optional(),
  description: z.string().optional(),
  isPrivate: z.boolean().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateRulesetRequestBody$ {
  /** @deprecated use `UpdateRulesetRequestBody$inboundSchema` instead. */
  export const inboundSchema = UpdateRulesetRequestBody$inboundSchema;
  /** @deprecated use `UpdateRulesetRequestBody$outboundSchema` instead. */
  export const outboundSchema = UpdateRulesetRequestBody$outboundSchema;
  /** @deprecated use `UpdateRulesetRequestBody$Outbound` instead. */
  export type Outbound = UpdateRulesetRequestBody$Outbound;
}

export function updateRulesetRequestBodyToJSON(
  updateRulesetRequestBody: UpdateRulesetRequestBody,
): string {
  return JSON.stringify(
    UpdateRulesetRequestBody$outboundSchema.parse(updateRulesetRequestBody),
  );
}

export function updateRulesetRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<UpdateRulesetRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateRulesetRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateRulesetRequestBody' from JSON`,
  );
}

/** @internal */
export const UpdateRulesetRequest$inboundSchema: z.ZodType<
  UpdateRulesetRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  namespace: z.string(),
  slug: z.string(),
  RequestBody: z.lazy(() => UpdateRulesetRequestBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type UpdateRulesetRequest$Outbound = {
  namespace: string;
  slug: string;
  RequestBody: UpdateRulesetRequestBody$Outbound;
};

/** @internal */
export const UpdateRulesetRequest$outboundSchema: z.ZodType<
  UpdateRulesetRequest$Outbound,
  z.ZodTypeDef,
  UpdateRulesetRequest
> = z.object({
  namespace: z.string(),
  slug: z.string(),
  requestBody: z.lazy(() => UpdateRulesetRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateRulesetRequest$ {
  /** @deprecated use `UpdateRulesetRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateRulesetRequest$inboundSchema;
  /** @deprecated use `UpdateRulesetRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateRulesetRequest$outboundSchema;
  /** @deprecated use `UpdateRulesetRequest$Outbound` instead. */
  export type Outbound = UpdateRulesetRequest$Outbound;
}

export function updateRulesetRequestToJSON(
  updateRulesetRequest: UpdateRulesetRequest,
): string {
  return JSON.stringify(
    UpdateRulesetRequest$outboundSchema.parse(updateRulesetRequest),
  );
}

export function updateRulesetRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateRulesetRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateRulesetRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateRulesetRequest' from JSON`,
  );
}

/** @internal */
export const UpdateRulesetResponse$inboundSchema: z.ZodType<
  UpdateRulesetResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  any: z.nullable(z.any()).optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
  });
});

/** @internal */
export type UpdateRulesetResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  any?: any | null | undefined;
};

/** @internal */
export const UpdateRulesetResponse$outboundSchema: z.ZodType<
  UpdateRulesetResponse$Outbound,
  z.ZodTypeDef,
  UpdateRulesetResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  any: z.nullable(z.any()).optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateRulesetResponse$ {
  /** @deprecated use `UpdateRulesetResponse$inboundSchema` instead. */
  export const inboundSchema = UpdateRulesetResponse$inboundSchema;
  /** @deprecated use `UpdateRulesetResponse$outboundSchema` instead. */
  export const outboundSchema = UpdateRulesetResponse$outboundSchema;
  /** @deprecated use `UpdateRulesetResponse$Outbound` instead. */
  export type Outbound = UpdateRulesetResponse$Outbound;
}

export function updateRulesetResponseToJSON(
  updateRulesetResponse: UpdateRulesetResponse,
): string {
  return JSON.stringify(
    UpdateRulesetResponse$outboundSchema.parse(updateRulesetResponse),
  );
}

export function updateRulesetResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateRulesetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateRulesetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateRulesetResponse' from JSON`,
  );
}
