/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateApiDocumentVersionRequestBody = {
  document: string;
  lastKnownVersionSha?: string | undefined;
};

export type UpdateApiDocumentVersionRequest = {
  namespace: string;
  slug: string;
  semver: string;
  requestBody: UpdateApiDocumentVersionRequestBody;
};

/**
 * Default Response
 */
export type UpdateApiDocumentVersionResponseBody = {
  jsonSha: string;
  yamlSha: string;
  versionSha: string;
};

/** @internal */
export const UpdateApiDocumentVersionRequestBody$inboundSchema: z.ZodType<
  UpdateApiDocumentVersionRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  document: z.string(),
  lastKnownVersionSha: z.string().optional(),
});

/** @internal */
export type UpdateApiDocumentVersionRequestBody$Outbound = {
  document: string;
  lastKnownVersionSha?: string | undefined;
};

/** @internal */
export const UpdateApiDocumentVersionRequestBody$outboundSchema: z.ZodType<
  UpdateApiDocumentVersionRequestBody$Outbound,
  z.ZodTypeDef,
  UpdateApiDocumentVersionRequestBody
> = z.object({
  document: z.string(),
  lastKnownVersionSha: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateApiDocumentVersionRequestBody$ {
  /** @deprecated use `UpdateApiDocumentVersionRequestBody$inboundSchema` instead. */
  export const inboundSchema =
    UpdateApiDocumentVersionRequestBody$inboundSchema;
  /** @deprecated use `UpdateApiDocumentVersionRequestBody$outboundSchema` instead. */
  export const outboundSchema =
    UpdateApiDocumentVersionRequestBody$outboundSchema;
  /** @deprecated use `UpdateApiDocumentVersionRequestBody$Outbound` instead. */
  export type Outbound = UpdateApiDocumentVersionRequestBody$Outbound;
}

export function updateApiDocumentVersionRequestBodyToJSON(
  updateApiDocumentVersionRequestBody: UpdateApiDocumentVersionRequestBody,
): string {
  return JSON.stringify(
    UpdateApiDocumentVersionRequestBody$outboundSchema.parse(
      updateApiDocumentVersionRequestBody,
    ),
  );
}

export function updateApiDocumentVersionRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<UpdateApiDocumentVersionRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateApiDocumentVersionRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateApiDocumentVersionRequestBody' from JSON`,
  );
}

/** @internal */
export const UpdateApiDocumentVersionRequest$inboundSchema: z.ZodType<
  UpdateApiDocumentVersionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  namespace: z.string(),
  slug: z.string(),
  semver: z.string(),
  RequestBody: z.lazy(() => UpdateApiDocumentVersionRequestBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type UpdateApiDocumentVersionRequest$Outbound = {
  namespace: string;
  slug: string;
  semver: string;
  RequestBody: UpdateApiDocumentVersionRequestBody$Outbound;
};

/** @internal */
export const UpdateApiDocumentVersionRequest$outboundSchema: z.ZodType<
  UpdateApiDocumentVersionRequest$Outbound,
  z.ZodTypeDef,
  UpdateApiDocumentVersionRequest
> = z.object({
  namespace: z.string(),
  slug: z.string(),
  semver: z.string(),
  requestBody: z.lazy(() => UpdateApiDocumentVersionRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateApiDocumentVersionRequest$ {
  /** @deprecated use `UpdateApiDocumentVersionRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateApiDocumentVersionRequest$inboundSchema;
  /** @deprecated use `UpdateApiDocumentVersionRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateApiDocumentVersionRequest$outboundSchema;
  /** @deprecated use `UpdateApiDocumentVersionRequest$Outbound` instead. */
  export type Outbound = UpdateApiDocumentVersionRequest$Outbound;
}

export function updateApiDocumentVersionRequestToJSON(
  updateApiDocumentVersionRequest: UpdateApiDocumentVersionRequest,
): string {
  return JSON.stringify(
    UpdateApiDocumentVersionRequest$outboundSchema.parse(
      updateApiDocumentVersionRequest,
    ),
  );
}

export function updateApiDocumentVersionRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateApiDocumentVersionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateApiDocumentVersionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateApiDocumentVersionRequest' from JSON`,
  );
}

/** @internal */
export const UpdateApiDocumentVersionResponseBody$inboundSchema: z.ZodType<
  UpdateApiDocumentVersionResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  jsonSha: z.string(),
  yamlSha: z.string(),
  versionSha: z.string(),
});

/** @internal */
export type UpdateApiDocumentVersionResponseBody$Outbound = {
  jsonSha: string;
  yamlSha: string;
  versionSha: string;
};

/** @internal */
export const UpdateApiDocumentVersionResponseBody$outboundSchema: z.ZodType<
  UpdateApiDocumentVersionResponseBody$Outbound,
  z.ZodTypeDef,
  UpdateApiDocumentVersionResponseBody
> = z.object({
  jsonSha: z.string(),
  yamlSha: z.string(),
  versionSha: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateApiDocumentVersionResponseBody$ {
  /** @deprecated use `UpdateApiDocumentVersionResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    UpdateApiDocumentVersionResponseBody$inboundSchema;
  /** @deprecated use `UpdateApiDocumentVersionResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    UpdateApiDocumentVersionResponseBody$outboundSchema;
  /** @deprecated use `UpdateApiDocumentVersionResponseBody$Outbound` instead. */
  export type Outbound = UpdateApiDocumentVersionResponseBody$Outbound;
}

export function updateApiDocumentVersionResponseBodyToJSON(
  updateApiDocumentVersionResponseBody: UpdateApiDocumentVersionResponseBody,
): string {
  return JSON.stringify(
    UpdateApiDocumentVersionResponseBody$outboundSchema.parse(
      updateApiDocumentVersionResponseBody,
    ),
  );
}

export function updateApiDocumentVersionResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<UpdateApiDocumentVersionResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateApiDocumentVersionResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateApiDocumentVersionResponseBody' from JSON`,
  );
}
