/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateApiDocumentRequestBody = {
  title?: string | undefined;
  description?: string | undefined;
  isPrivate?: boolean | undefined;
  ruleset?: string | undefined;
};

export type UpdateApiDocumentRequest = {
  namespace: string;
  slug: string;
  requestBody: UpdateApiDocumentRequestBody;
};

export type UpdateApiDocumentResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Default Response
   */
  any?: any | null | undefined;
};

/** @internal */
export const UpdateApiDocumentRequestBody$inboundSchema: z.ZodType<
  UpdateApiDocumentRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  title: z.string().optional(),
  description: z.string().optional(),
  isPrivate: z.boolean().optional(),
  ruleset: z.string().optional(),
});

/** @internal */
export type UpdateApiDocumentRequestBody$Outbound = {
  title?: string | undefined;
  description?: string | undefined;
  isPrivate?: boolean | undefined;
  ruleset?: string | undefined;
};

/** @internal */
export const UpdateApiDocumentRequestBody$outboundSchema: z.ZodType<
  UpdateApiDocumentRequestBody$Outbound,
  z.ZodTypeDef,
  UpdateApiDocumentRequestBody
> = z.object({
  title: z.string().optional(),
  description: z.string().optional(),
  isPrivate: z.boolean().optional(),
  ruleset: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateApiDocumentRequestBody$ {
  /** @deprecated use `UpdateApiDocumentRequestBody$inboundSchema` instead. */
  export const inboundSchema = UpdateApiDocumentRequestBody$inboundSchema;
  /** @deprecated use `UpdateApiDocumentRequestBody$outboundSchema` instead. */
  export const outboundSchema = UpdateApiDocumentRequestBody$outboundSchema;
  /** @deprecated use `UpdateApiDocumentRequestBody$Outbound` instead. */
  export type Outbound = UpdateApiDocumentRequestBody$Outbound;
}

export function updateApiDocumentRequestBodyToJSON(
  updateApiDocumentRequestBody: UpdateApiDocumentRequestBody,
): string {
  return JSON.stringify(
    UpdateApiDocumentRequestBody$outboundSchema.parse(
      updateApiDocumentRequestBody,
    ),
  );
}

export function updateApiDocumentRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<UpdateApiDocumentRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateApiDocumentRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateApiDocumentRequestBody' from JSON`,
  );
}

/** @internal */
export const UpdateApiDocumentRequest$inboundSchema: z.ZodType<
  UpdateApiDocumentRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  namespace: z.string(),
  slug: z.string(),
  RequestBody: z.lazy(() => UpdateApiDocumentRequestBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type UpdateApiDocumentRequest$Outbound = {
  namespace: string;
  slug: string;
  RequestBody: UpdateApiDocumentRequestBody$Outbound;
};

/** @internal */
export const UpdateApiDocumentRequest$outboundSchema: z.ZodType<
  UpdateApiDocumentRequest$Outbound,
  z.ZodTypeDef,
  UpdateApiDocumentRequest
> = z.object({
  namespace: z.string(),
  slug: z.string(),
  requestBody: z.lazy(() => UpdateApiDocumentRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateApiDocumentRequest$ {
  /** @deprecated use `UpdateApiDocumentRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateApiDocumentRequest$inboundSchema;
  /** @deprecated use `UpdateApiDocumentRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateApiDocumentRequest$outboundSchema;
  /** @deprecated use `UpdateApiDocumentRequest$Outbound` instead. */
  export type Outbound = UpdateApiDocumentRequest$Outbound;
}

export function updateApiDocumentRequestToJSON(
  updateApiDocumentRequest: UpdateApiDocumentRequest,
): string {
  return JSON.stringify(
    UpdateApiDocumentRequest$outboundSchema.parse(updateApiDocumentRequest),
  );
}

export function updateApiDocumentRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateApiDocumentRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateApiDocumentRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateApiDocumentRequest' from JSON`,
  );
}

/** @internal */
export const UpdateApiDocumentResponse$inboundSchema: z.ZodType<
  UpdateApiDocumentResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  any: z.nullable(z.any()).optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
  });
});

/** @internal */
export type UpdateApiDocumentResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  any?: any | null | undefined;
};

/** @internal */
export const UpdateApiDocumentResponse$outboundSchema: z.ZodType<
  UpdateApiDocumentResponse$Outbound,
  z.ZodTypeDef,
  UpdateApiDocumentResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  any: z.nullable(z.any()).optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateApiDocumentResponse$ {
  /** @deprecated use `UpdateApiDocumentResponse$inboundSchema` instead. */
  export const inboundSchema = UpdateApiDocumentResponse$inboundSchema;
  /** @deprecated use `UpdateApiDocumentResponse$outboundSchema` instead. */
  export const outboundSchema = UpdateApiDocumentResponse$outboundSchema;
  /** @deprecated use `UpdateApiDocumentResponse$Outbound` instead. */
  export type Outbound = UpdateApiDocumentResponse$Outbound;
}

export function updateApiDocumentResponseToJSON(
  updateApiDocumentResponse: UpdateApiDocumentResponse,
): string {
  return JSON.stringify(
    UpdateApiDocumentResponse$outboundSchema.parse(updateApiDocumentResponse),
  );
}

export function updateApiDocumentResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateApiDocumentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateApiDocumentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateApiDocumentResponse' from JSON`,
  );
}
