/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateSchemaRequestBody = {
  title?: string | undefined;
  description?: string | undefined;
  isPrivate?: boolean | undefined;
};

export type UpdateSchemaRequest = {
  namespace: string;
  slug: string;
  requestBody: UpdateSchemaRequestBody;
};

/** @internal */
export const UpdateSchemaRequestBody$inboundSchema: z.ZodType<
  UpdateSchemaRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  title: z.string().optional(),
  description: z.string().optional(),
  isPrivate: z.boolean().optional(),
});

/** @internal */
export type UpdateSchemaRequestBody$Outbound = {
  title?: string | undefined;
  description?: string | undefined;
  isPrivate?: boolean | undefined;
};

/** @internal */
export const UpdateSchemaRequestBody$outboundSchema: z.ZodType<
  UpdateSchemaRequestBody$Outbound,
  z.ZodTypeDef,
  UpdateSchemaRequestBody
> = z.object({
  title: z.string().optional(),
  description: z.string().optional(),
  isPrivate: z.boolean().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateSchemaRequestBody$ {
  /** @deprecated use `UpdateSchemaRequestBody$inboundSchema` instead. */
  export const inboundSchema = UpdateSchemaRequestBody$inboundSchema;
  /** @deprecated use `UpdateSchemaRequestBody$outboundSchema` instead. */
  export const outboundSchema = UpdateSchemaRequestBody$outboundSchema;
  /** @deprecated use `UpdateSchemaRequestBody$Outbound` instead. */
  export type Outbound = UpdateSchemaRequestBody$Outbound;
}

export function updateSchemaRequestBodyToJSON(
  updateSchemaRequestBody: UpdateSchemaRequestBody,
): string {
  return JSON.stringify(
    UpdateSchemaRequestBody$outboundSchema.parse(updateSchemaRequestBody),
  );
}

export function updateSchemaRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<UpdateSchemaRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateSchemaRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateSchemaRequestBody' from JSON`,
  );
}

/** @internal */
export const UpdateSchemaRequest$inboundSchema: z.ZodType<
  UpdateSchemaRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  namespace: z.string(),
  slug: z.string(),
  RequestBody: z.lazy(() => UpdateSchemaRequestBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type UpdateSchemaRequest$Outbound = {
  namespace: string;
  slug: string;
  RequestBody: UpdateSchemaRequestBody$Outbound;
};

/** @internal */
export const UpdateSchemaRequest$outboundSchema: z.ZodType<
  UpdateSchemaRequest$Outbound,
  z.ZodTypeDef,
  UpdateSchemaRequest
> = z.object({
  namespace: z.string(),
  slug: z.string(),
  requestBody: z.lazy(() => UpdateSchemaRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateSchemaRequest$ {
  /** @deprecated use `UpdateSchemaRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateSchemaRequest$inboundSchema;
  /** @deprecated use `UpdateSchemaRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateSchemaRequest$outboundSchema;
  /** @deprecated use `UpdateSchemaRequest$Outbound` instead. */
  export type Outbound = UpdateSchemaRequest$Outbound;
}

export function updateSchemaRequestToJSON(
  updateSchemaRequest: UpdateSchemaRequest,
): string {
  return JSON.stringify(
    UpdateSchemaRequest$outboundSchema.parse(updateSchemaRequest),
  );
}

export function updateSchemaRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateSchemaRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateSchemaRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateSchemaRequest' from JSON`,
  );
}
