/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateLoginPortalRequestBody = {
  title?: string | undefined;
};

export type UpdateLoginPortalRequest = {
  slug: string;
  requestBody: UpdateLoginPortalRequestBody;
};

/** @internal */
export const UpdateLoginPortalRequestBody$inboundSchema: z.ZodType<
  UpdateLoginPortalRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  title: z.string().optional(),
});

/** @internal */
export type UpdateLoginPortalRequestBody$Outbound = {
  title?: string | undefined;
};

/** @internal */
export const UpdateLoginPortalRequestBody$outboundSchema: z.ZodType<
  UpdateLoginPortalRequestBody$Outbound,
  z.ZodTypeDef,
  UpdateLoginPortalRequestBody
> = z.object({
  title: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateLoginPortalRequestBody$ {
  /** @deprecated use `UpdateLoginPortalRequestBody$inboundSchema` instead. */
  export const inboundSchema = UpdateLoginPortalRequestBody$inboundSchema;
  /** @deprecated use `UpdateLoginPortalRequestBody$outboundSchema` instead. */
  export const outboundSchema = UpdateLoginPortalRequestBody$outboundSchema;
  /** @deprecated use `UpdateLoginPortalRequestBody$Outbound` instead. */
  export type Outbound = UpdateLoginPortalRequestBody$Outbound;
}

export function updateLoginPortalRequestBodyToJSON(
  updateLoginPortalRequestBody: UpdateLoginPortalRequestBody,
): string {
  return JSON.stringify(
    UpdateLoginPortalRequestBody$outboundSchema.parse(
      updateLoginPortalRequestBody,
    ),
  );
}

export function updateLoginPortalRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<UpdateLoginPortalRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateLoginPortalRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateLoginPortalRequestBody' from JSON`,
  );
}

/** @internal */
export const UpdateLoginPortalRequest$inboundSchema: z.ZodType<
  UpdateLoginPortalRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  slug: z.string(),
  RequestBody: z.lazy(() => UpdateLoginPortalRequestBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type UpdateLoginPortalRequest$Outbound = {
  slug: string;
  RequestBody: UpdateLoginPortalRequestBody$Outbound;
};

/** @internal */
export const UpdateLoginPortalRequest$outboundSchema: z.ZodType<
  UpdateLoginPortalRequest$Outbound,
  z.ZodTypeDef,
  UpdateLoginPortalRequest
> = z.object({
  slug: z.string(),
  requestBody: z.lazy(() => UpdateLoginPortalRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateLoginPortalRequest$ {
  /** @deprecated use `UpdateLoginPortalRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateLoginPortalRequest$inboundSchema;
  /** @deprecated use `UpdateLoginPortalRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateLoginPortalRequest$outboundSchema;
  /** @deprecated use `UpdateLoginPortalRequest$Outbound` instead. */
  export type Outbound = UpdateLoginPortalRequest$Outbound;
}

export function updateLoginPortalRequestToJSON(
  updateLoginPortalRequest: UpdateLoginPortalRequest,
): string {
  return JSON.stringify(
    UpdateLoginPortalRequest$outboundSchema.parse(updateLoginPortalRequest),
  );
}

export function updateLoginPortalRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateLoginPortalRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateLoginPortalRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateLoginPortalRequest' from JSON`,
  );
}
