/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GithubProjectRepository = {
  linkedBy: string;
  id: number;
  name: string;
  configPath?: string | undefined;
  branch?: string | undefined;
  publishOnMerge?: boolean | undefined;
  publishPreviews?: boolean | undefined;
  prComments?: boolean | undefined;
  expired?: boolean | undefined;
};

/** @internal */
export const GithubProjectRepository$inboundSchema: z.ZodType<
  GithubProjectRepository,
  z.ZodTypeDef,
  unknown
> = z.object({
  linkedBy: z.string(),
  id: z.number(),
  name: z.string(),
  configPath: z.string().default(""),
  branch: z.string().default(""),
  publishOnMerge: z.boolean().default(false),
  publishPreviews: z.boolean().default(false),
  prComments: z.boolean().default(false),
  expired: z.boolean().default(false),
});

/** @internal */
export type GithubProjectRepository$Outbound = {
  linkedBy: string;
  id: number;
  name: string;
  configPath: string;
  branch: string;
  publishOnMerge: boolean;
  publishPreviews: boolean;
  prComments: boolean;
  expired: boolean;
};

/** @internal */
export const GithubProjectRepository$outboundSchema: z.ZodType<
  GithubProjectRepository$Outbound,
  z.ZodTypeDef,
  GithubProjectRepository
> = z.object({
  linkedBy: z.string(),
  id: z.number(),
  name: z.string(),
  configPath: z.string().default(""),
  branch: z.string().default(""),
  publishOnMerge: z.boolean().default(false),
  publishPreviews: z.boolean().default(false),
  prComments: z.boolean().default(false),
  expired: z.boolean().default(false),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GithubProjectRepository$ {
  /** @deprecated use `GithubProjectRepository$inboundSchema` instead. */
  export const inboundSchema = GithubProjectRepository$inboundSchema;
  /** @deprecated use `GithubProjectRepository$outboundSchema` instead. */
  export const outboundSchema = GithubProjectRepository$outboundSchema;
  /** @deprecated use `GithubProjectRepository$Outbound` instead. */
  export type Outbound = GithubProjectRepository$Outbound;
}

export function githubProjectRepositoryToJSON(
  githubProjectRepository: GithubProjectRepository,
): string {
  return JSON.stringify(
    GithubProjectRepository$outboundSchema.parse(githubProjectRepository),
  );
}

export function githubProjectRepositoryFromJSON(
  jsonString: string,
): SafeParseResult<GithubProjectRepository, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GithubProjectRepository$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GithubProjectRepository' from JSON`,
  );
}
