/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ActiveDeployment,
  ActiveDeployment$inboundSchema,
  ActiveDeployment$Outbound,
  ActiveDeployment$outboundSchema,
} from "./activedeployment.js";
import {
  GithubProjectRepository,
  GithubProjectRepository$inboundSchema,
  GithubProjectRepository$Outbound,
  GithubProjectRepository$outboundSchema,
} from "./githubprojectrepository.js";

export type GithubProject = {
  uid: string;
  createdAt: number;
  updatedAt: number;
  name: string;
  activeDeployment: ActiveDeployment | null;
  lastPublished: number | null;
  lastPublishedUid: string | null;
  loginPortalUid?: string | undefined;
  activeThemeId?: string | undefined;
  typesenseId?: number | undefined;
  isPrivate?: boolean | undefined;
  agentEnabled?: boolean | undefined;
  accessGroups?: any | undefined;
  slug: string;
  publishStatus?: string | undefined;
  publishMessage?: string | undefined;
  repository?: GithubProjectRepository | null | undefined;
};

/** @internal */
export const GithubProject$inboundSchema: z.ZodType<
  GithubProject,
  z.ZodTypeDef,
  unknown
> = z.object({
  uid: z.string(),
  createdAt: z.number().int(),
  updatedAt: z.number().int(),
  name: z.string(),
  activeDeployment: z.nullable(ActiveDeployment$inboundSchema),
  lastPublished: z.nullable(z.number().int()),
  lastPublishedUid: z.nullable(z.string()),
  loginPortalUid: z.string().default(""),
  activeThemeId: z.string().default(""),
  typesenseId: z.number().optional(),
  isPrivate: z.boolean().default(false),
  agentEnabled: z.boolean().default(false),
  accessGroups: z.any(),
  slug: z.string(),
  publishStatus: z.string().default(""),
  publishMessage: z.string().default(""),
  repository: z.nullable(GithubProjectRepository$inboundSchema).optional(),
});

/** @internal */
export type GithubProject$Outbound = {
  uid: string;
  createdAt: number;
  updatedAt: number;
  name: string;
  activeDeployment: ActiveDeployment$Outbound | null;
  lastPublished: number | null;
  lastPublishedUid: string | null;
  loginPortalUid: string;
  activeThemeId: string;
  typesenseId?: number | undefined;
  isPrivate: boolean;
  agentEnabled: boolean;
  accessGroups?: any;
  slug: string;
  publishStatus: string;
  publishMessage: string;
  repository?: GithubProjectRepository$Outbound | null | undefined;
};

/** @internal */
export const GithubProject$outboundSchema: z.ZodType<
  GithubProject$Outbound,
  z.ZodTypeDef,
  GithubProject
> = z.object({
  uid: z.string(),
  createdAt: z.number().int(),
  updatedAt: z.number().int(),
  name: z.string(),
  activeDeployment: z.nullable(ActiveDeployment$outboundSchema),
  lastPublished: z.nullable(z.number().int()),
  lastPublishedUid: z.nullable(z.string()),
  loginPortalUid: z.string().default(""),
  activeThemeId: z.string().default(""),
  typesenseId: z.number().optional(),
  isPrivate: z.boolean().default(false),
  agentEnabled: z.boolean().default(false),
  accessGroups: z.any(),
  slug: z.string(),
  publishStatus: z.string().default(""),
  publishMessage: z.string().default(""),
  repository: z.nullable(GithubProjectRepository$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GithubProject$ {
  /** @deprecated use `GithubProject$inboundSchema` instead. */
  export const inboundSchema = GithubProject$inboundSchema;
  /** @deprecated use `GithubProject$outboundSchema` instead. */
  export const outboundSchema = GithubProject$outboundSchema;
  /** @deprecated use `GithubProject$Outbound` instead. */
  export type Outbound = GithubProject$Outbound;
}

export function githubProjectToJSON(githubProject: GithubProject): string {
  return JSON.stringify(GithubProject$outboundSchema.parse(githubProject));
}

export function githubProjectFromJSON(
  jsonString: string,
): SafeParseResult<GithubProject, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GithubProject$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GithubProject' from JSON`,
  );
}
