/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LoginPortalEmail = {
  logo?: string | undefined;
  logoSize?: string | undefined;
  buttonText?: string | undefined;
  message?: string | undefined;
  title?: string | undefined;
  mainColor?: string | undefined;
  mainBackground?: string | undefined;
  cardColor?: string | undefined;
  cardBackground?: string | undefined;
  buttonColor?: string | undefined;
  buttonBackground?: string | undefined;
};

/** @internal */
export const LoginPortalEmail$inboundSchema: z.ZodType<
  LoginPortalEmail,
  z.ZodTypeDef,
  unknown
> = z.object({
  logo: z.string().default(""),
  logoSize: z.string().default("100"),
  buttonText: z.string().default("Login"),
  message: z.string().default(
    "Click to access private documentation hosted by scalar.com",
  ),
  title: z.string().default("Private Docs"),
  mainColor: z.string().default("#2a2f45"),
  mainBackground: z.string().default("#f6f6f6"),
  cardColor: z.string().default("2a2f45"),
  cardBackground: z.string().default("#fff"),
  buttonColor: z.string().default("#fff"),
  buttonBackground: z.string().default("#0f0f0f"),
});

/** @internal */
export type LoginPortalEmail$Outbound = {
  logo: string;
  logoSize: string;
  buttonText: string;
  message: string;
  title: string;
  mainColor: string;
  mainBackground: string;
  cardColor: string;
  cardBackground: string;
  buttonColor: string;
  buttonBackground: string;
};

/** @internal */
export const LoginPortalEmail$outboundSchema: z.ZodType<
  LoginPortalEmail$Outbound,
  z.ZodTypeDef,
  LoginPortalEmail
> = z.object({
  logo: z.string().default(""),
  logoSize: z.string().default("100"),
  buttonText: z.string().default("Login"),
  message: z.string().default(
    "Click to access private documentation hosted by scalar.com",
  ),
  title: z.string().default("Private Docs"),
  mainColor: z.string().default("#2a2f45"),
  mainBackground: z.string().default("#f6f6f6"),
  cardColor: z.string().default("2a2f45"),
  cardBackground: z.string().default("#fff"),
  buttonColor: z.string().default("#fff"),
  buttonBackground: z.string().default("#0f0f0f"),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LoginPortalEmail$ {
  /** @deprecated use `LoginPortalEmail$inboundSchema` instead. */
  export const inboundSchema = LoginPortalEmail$inboundSchema;
  /** @deprecated use `LoginPortalEmail$outboundSchema` instead. */
  export const outboundSchema = LoginPortalEmail$outboundSchema;
  /** @deprecated use `LoginPortalEmail$Outbound` instead. */
  export type Outbound = LoginPortalEmail$Outbound;
}

export function loginPortalEmailToJSON(
  loginPortalEmail: LoginPortalEmail,
): string {
  return JSON.stringify(
    LoginPortalEmail$outboundSchema.parse(loginPortalEmail),
  );
}

export function loginPortalEmailFromJSON(
  jsonString: string,
): SafeParseResult<LoginPortalEmail, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LoginPortalEmail$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LoginPortalEmail' from JSON`,
  );
}
