/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LoginPortal = {
  uid: string;
  title: string;
  slug: string;
};

/** @internal */
export const LoginPortal$inboundSchema: z.ZodType<
  LoginPortal,
  z.ZodTypeDef,
  unknown
> = z.object({
  uid: z.string(),
  title: z.string(),
  slug: z.string(),
});

/** @internal */
export type LoginPortal$Outbound = {
  uid: string;
  title: string;
  slug: string;
};

/** @internal */
export const LoginPortal$outboundSchema: z.ZodType<
  LoginPortal$Outbound,
  z.ZodTypeDef,
  LoginPortal
> = z.object({
  uid: z.string(),
  title: z.string(),
  slug: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LoginPortal$ {
  /** @deprecated use `LoginPortal$inboundSchema` instead. */
  export const inboundSchema = LoginPortal$inboundSchema;
  /** @deprecated use `LoginPortal$outboundSchema` instead. */
  export const outboundSchema = LoginPortal$outboundSchema;
  /** @deprecated use `LoginPortal$Outbound` instead. */
  export type Outbound = LoginPortal$Outbound;
}

export function loginPortalToJSON(loginPortal: LoginPortal): string {
  return JSON.stringify(LoginPortal$outboundSchema.parse(loginPortal));
}

export function loginPortalFromJSON(
  jsonString: string,
): SafeParseResult<LoginPortal, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LoginPortal$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LoginPortal' from JSON`,
  );
}
