/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LoginPortalPage = {
  title?: string | undefined;
  description?: string | undefined;
  head?: string | undefined;
  script?: string | undefined;
  theme?: string | undefined;
  companyName?: string | undefined;
  logo?: string | undefined;
  logoURL?: string | undefined;
  favicon?: string | undefined;
  termsLink?: string | undefined;
  privacyLink?: string | undefined;
  formTitle?: string | undefined;
  formDescription?: string | undefined;
  formImage?: string | undefined;
};

/** @internal */
export const LoginPortalPage$inboundSchema: z.ZodType<
  LoginPortalPage,
  z.ZodTypeDef,
  unknown
> = z.object({
  title: z.string().default("Scalar Private Docs"),
  description: z.string().default("Login to access your documentation"),
  head: z.string().default(""),
  script: z.string().default(""),
  theme: z.string().default(""),
  companyName: z.string().default(""),
  logo: z.string().default(""),
  logoURL: z.string().default(""),
  favicon: z.string().default(""),
  termsLink: z.string().default(""),
  privacyLink: z.string().default(""),
  formTitle: z.string().default("Scalar Private Docs"),
  formDescription: z.string().default("Login to access your documentation"),
  formImage: z.string().default(""),
});

/** @internal */
export type LoginPortalPage$Outbound = {
  title: string;
  description: string;
  head: string;
  script: string;
  theme: string;
  companyName: string;
  logo: string;
  logoURL: string;
  favicon: string;
  termsLink: string;
  privacyLink: string;
  formTitle: string;
  formDescription: string;
  formImage: string;
};

/** @internal */
export const LoginPortalPage$outboundSchema: z.ZodType<
  LoginPortalPage$Outbound,
  z.ZodTypeDef,
  LoginPortalPage
> = z.object({
  title: z.string().default("Scalar Private Docs"),
  description: z.string().default("Login to access your documentation"),
  head: z.string().default(""),
  script: z.string().default(""),
  theme: z.string().default(""),
  companyName: z.string().default(""),
  logo: z.string().default(""),
  logoURL: z.string().default(""),
  favicon: z.string().default(""),
  termsLink: z.string().default(""),
  privacyLink: z.string().default(""),
  formTitle: z.string().default("Scalar Private Docs"),
  formDescription: z.string().default("Login to access your documentation"),
  formImage: z.string().default(""),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LoginPortalPage$ {
  /** @deprecated use `LoginPortalPage$inboundSchema` instead. */
  export const inboundSchema = LoginPortalPage$inboundSchema;
  /** @deprecated use `LoginPortalPage$outboundSchema` instead. */
  export const outboundSchema = LoginPortalPage$outboundSchema;
  /** @deprecated use `LoginPortalPage$Outbound` instead. */
  export type Outbound = LoginPortalPage$Outbound;
}

export function loginPortalPageToJSON(
  loginPortalPage: LoginPortalPage,
): string {
  return JSON.stringify(LoginPortalPage$outboundSchema.parse(loginPortalPage));
}

export function loginPortalPageFromJSON(
  jsonString: string,
): SafeParseResult<LoginPortalPage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LoginPortalPage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LoginPortalPage' from JSON`,
  );
}
