/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ManagedSchemaVersion = {
  uid: string;
  createdAt: number;
  updatedAt: number;
  version: string;
};

/** @internal */
export const ManagedSchemaVersion$inboundSchema: z.ZodType<
  ManagedSchemaVersion,
  z.ZodTypeDef,
  unknown
> = z.object({
  uid: z.string(),
  createdAt: z.number().int(),
  updatedAt: z.number().int(),
  version: z.string(),
});

/** @internal */
export type ManagedSchemaVersion$Outbound = {
  uid: string;
  createdAt: number;
  updatedAt: number;
  version: string;
};

/** @internal */
export const ManagedSchemaVersion$outboundSchema: z.ZodType<
  ManagedSchemaVersion$Outbound,
  z.ZodTypeDef,
  ManagedSchemaVersion
> = z.object({
  uid: z.string(),
  createdAt: z.number().int(),
  updatedAt: z.number().int(),
  version: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ManagedSchemaVersion$ {
  /** @deprecated use `ManagedSchemaVersion$inboundSchema` instead. */
  export const inboundSchema = ManagedSchemaVersion$inboundSchema;
  /** @deprecated use `ManagedSchemaVersion$outboundSchema` instead. */
  export const outboundSchema = ManagedSchemaVersion$outboundSchema;
  /** @deprecated use `ManagedSchemaVersion$Outbound` instead. */
  export type Outbound = ManagedSchemaVersion$Outbound;
}

export function managedSchemaVersionToJSON(
  managedSchemaVersion: ManagedSchemaVersion,
): string {
  return JSON.stringify(
    ManagedSchemaVersion$outboundSchema.parse(managedSchemaVersion),
  );
}

export function managedSchemaVersionFromJSON(
  jsonString: string,
): SafeParseResult<ManagedSchemaVersion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ManagedSchemaVersion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ManagedSchemaVersion' from JSON`,
  );
}
