/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  Method,
  Method$inboundSchema,
  Method$outboundSchema,
} from "./method.js";

export const EmbedStatus = {
  Complete: "complete",
  Failed: "failed",
} as const;
export type EmbedStatus = ClosedEnum<typeof EmbedStatus>;

export const EnabledTools = {
  ExecuteRequest: "execute-request",
  GetMiniOpenapiSpec: "get-mini-openapi-spec",
} as const;
export type EnabledTools = ClosedEnum<typeof EnabledTools>;

export type Tools = {
  path: string;
  method: Method;
  enabledTools: Array<EnabledTools>;
};

export type ManagedDocVersion = {
  uid: string;
  createdAt: number;
  version: string;
  upgraded?: boolean | undefined;
  embedStatus: EmbedStatus | null;
  tags: Array<string>;
  tools?: Array<Tools> | undefined;
  yamlSha?: string | undefined;
  jsonSha?: string | undefined;
};

/** @internal */
export const EmbedStatus$inboundSchema: z.ZodNativeEnum<typeof EmbedStatus> = z
  .nativeEnum(EmbedStatus);

/** @internal */
export const EmbedStatus$outboundSchema: z.ZodNativeEnum<typeof EmbedStatus> =
  EmbedStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EmbedStatus$ {
  /** @deprecated use `EmbedStatus$inboundSchema` instead. */
  export const inboundSchema = EmbedStatus$inboundSchema;
  /** @deprecated use `EmbedStatus$outboundSchema` instead. */
  export const outboundSchema = EmbedStatus$outboundSchema;
}

/** @internal */
export const EnabledTools$inboundSchema: z.ZodNativeEnum<typeof EnabledTools> =
  z.nativeEnum(EnabledTools);

/** @internal */
export const EnabledTools$outboundSchema: z.ZodNativeEnum<typeof EnabledTools> =
  EnabledTools$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EnabledTools$ {
  /** @deprecated use `EnabledTools$inboundSchema` instead. */
  export const inboundSchema = EnabledTools$inboundSchema;
  /** @deprecated use `EnabledTools$outboundSchema` instead. */
  export const outboundSchema = EnabledTools$outboundSchema;
}

/** @internal */
export const Tools$inboundSchema: z.ZodType<Tools, z.ZodTypeDef, unknown> = z
  .object({
    path: z.string(),
    method: Method$inboundSchema,
    enabledTools: z.array(EnabledTools$inboundSchema),
  });

/** @internal */
export type Tools$Outbound = {
  path: string;
  method: string;
  enabledTools: Array<string>;
};

/** @internal */
export const Tools$outboundSchema: z.ZodType<
  Tools$Outbound,
  z.ZodTypeDef,
  Tools
> = z.object({
  path: z.string(),
  method: Method$outboundSchema,
  enabledTools: z.array(EnabledTools$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Tools$ {
  /** @deprecated use `Tools$inboundSchema` instead. */
  export const inboundSchema = Tools$inboundSchema;
  /** @deprecated use `Tools$outboundSchema` instead. */
  export const outboundSchema = Tools$outboundSchema;
  /** @deprecated use `Tools$Outbound` instead. */
  export type Outbound = Tools$Outbound;
}

export function toolsToJSON(tools: Tools): string {
  return JSON.stringify(Tools$outboundSchema.parse(tools));
}

export function toolsFromJSON(
  jsonString: string,
): SafeParseResult<Tools, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Tools$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Tools' from JSON`,
  );
}

/** @internal */
export const ManagedDocVersion$inboundSchema: z.ZodType<
  ManagedDocVersion,
  z.ZodTypeDef,
  unknown
> = z.object({
  uid: z.string(),
  createdAt: z.number(),
  version: z.string(),
  upgraded: z.boolean().default(false),
  embedStatus: z.nullable(EmbedStatus$inboundSchema),
  tags: z.array(z.string()),
  tools: z.array(z.lazy(() => Tools$inboundSchema)).optional(),
  yamlSha: z.string().optional(),
  jsonSha: z.string().optional(),
});

/** @internal */
export type ManagedDocVersion$Outbound = {
  uid: string;
  createdAt: number;
  version: string;
  upgraded: boolean;
  embedStatus: string | null;
  tags: Array<string>;
  tools?: Array<Tools$Outbound> | undefined;
  yamlSha?: string | undefined;
  jsonSha?: string | undefined;
};

/** @internal */
export const ManagedDocVersion$outboundSchema: z.ZodType<
  ManagedDocVersion$Outbound,
  z.ZodTypeDef,
  ManagedDocVersion
> = z.object({
  uid: z.string(),
  createdAt: z.number(),
  version: z.string(),
  upgraded: z.boolean().default(false),
  embedStatus: z.nullable(EmbedStatus$outboundSchema),
  tags: z.array(z.string()),
  tools: z.array(z.lazy(() => Tools$outboundSchema)).optional(),
  yamlSha: z.string().optional(),
  jsonSha: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ManagedDocVersion$ {
  /** @deprecated use `ManagedDocVersion$inboundSchema` instead. */
  export const inboundSchema = ManagedDocVersion$inboundSchema;
  /** @deprecated use `ManagedDocVersion$outboundSchema` instead. */
  export const outboundSchema = ManagedDocVersion$outboundSchema;
  /** @deprecated use `ManagedDocVersion$Outbound` instead. */
  export type Outbound = ManagedDocVersion$Outbound;
}

export function managedDocVersionToJSON(
  managedDocVersion: ManagedDocVersion,
): string {
  return JSON.stringify(
    ManagedDocVersion$outboundSchema.parse(managedDocVersion),
  );
}

export function managedDocVersionFromJSON(
  jsonString: string,
): SafeParseResult<ManagedDocVersion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ManagedDocVersion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ManagedDocVersion' from JSON`,
  );
}
