/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ManagedSchemaVersion,
  ManagedSchemaVersion$inboundSchema,
  ManagedSchemaVersion$Outbound,
  ManagedSchemaVersion$outboundSchema,
} from "./managedschemaversion.js";

export type Schema = {
  uid: string;
  title?: string | undefined;
  description?: string | undefined;
  slug: string;
  namespace: string;
  isPrivate?: boolean | undefined;
  versions: Array<ManagedSchemaVersion>;
};

/** @internal */
export const Schema$inboundSchema: z.ZodType<Schema, z.ZodTypeDef, unknown> = z
  .object({
    uid: z.string(),
    title: z.string().default(""),
    description: z.string().default(""),
    slug: z.string(),
    namespace: z.string(),
    isPrivate: z.boolean().default(false),
    versions: z.array(ManagedSchemaVersion$inboundSchema),
  });

/** @internal */
export type Schema$Outbound = {
  uid: string;
  title: string;
  description: string;
  slug: string;
  namespace: string;
  isPrivate: boolean;
  versions: Array<ManagedSchemaVersion$Outbound>;
};

/** @internal */
export const Schema$outboundSchema: z.ZodType<
  Schema$Outbound,
  z.ZodTypeDef,
  Schema
> = z.object({
  uid: z.string(),
  title: z.string().default(""),
  description: z.string().default(""),
  slug: z.string(),
  namespace: z.string(),
  isPrivate: z.boolean().default(false),
  versions: z.array(ManagedSchemaVersion$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Schema$ {
  /** @deprecated use `Schema$inboundSchema` instead. */
  export const inboundSchema = Schema$inboundSchema;
  /** @deprecated use `Schema$outboundSchema` instead. */
  export const outboundSchema = Schema$outboundSchema;
  /** @deprecated use `Schema$Outbound` instead. */
  export type Outbound = Schema$Outbound;
}

export function schemaToJSON(schema: Schema): string {
  return JSON.stringify(Schema$outboundSchema.parse(schema));
}

export function schemaFromJSON(
  jsonString: string,
): SafeParseResult<Schema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Schema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Schema' from JSON`,
  );
}
