/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Uid = {
  uid: string;
};

/** @internal */
export const Uid$inboundSchema: z.ZodType<Uid, z.ZodTypeDef, unknown> = z
  .object({
    uid: z.string(),
  });

/** @internal */
export type Uid$Outbound = {
  uid: string;
};

/** @internal */
export const Uid$outboundSchema: z.ZodType<Uid$Outbound, z.ZodTypeDef, Uid> = z
  .object({
    uid: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Uid$ {
  /** @deprecated use `Uid$inboundSchema` instead. */
  export const inboundSchema = Uid$inboundSchema;
  /** @deprecated use `Uid$outboundSchema` instead. */
  export const outboundSchema = Uid$outboundSchema;
  /** @deprecated use `Uid$Outbound` instead. */
  export type Outbound = Uid$Outbound;
}

export function uidToJSON(uid: Uid): string {
  return JSON.stringify(Uid$outboundSchema.parse(uid));
}

export function uidFromJSON(
  jsonString: string,
): SafeParseResult<Uid, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Uid$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Uid' from JSON`,
  );
}
