/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  TeamSummary,
  TeamSummary$inboundSchema,
  TeamSummary$Outbound,
  TeamSummary$outboundSchema,
} from "./teamsummary.js";

export type User = {
  uid: string;
  createdAt: number;
  updatedAt: number;
  email: string;
  theme?: string | undefined;
  activeTeamId: string | null;
  hasGithub?: boolean | undefined;
  teams: Array<TeamSummary>;
};

/** @internal */
export const User$inboundSchema: z.ZodType<User, z.ZodTypeDef, unknown> = z
  .object({
    uid: z.string(),
    createdAt: z.number().int(),
    updatedAt: z.number().int(),
    email: z.string(),
    theme: z.string().optional(),
    activeTeamId: z.nullable(z.string()),
    hasGithub: z.boolean().default(false),
    teams: z.array(TeamSummary$inboundSchema),
  });

/** @internal */
export type User$Outbound = {
  uid: string;
  createdAt: number;
  updatedAt: number;
  email: string;
  theme?: string | undefined;
  activeTeamId: string | null;
  hasGithub: boolean;
  teams: Array<TeamSummary$Outbound>;
};

/** @internal */
export const User$outboundSchema: z.ZodType<User$Outbound, z.ZodTypeDef, User> =
  z.object({
    uid: z.string(),
    createdAt: z.number().int(),
    updatedAt: z.number().int(),
    email: z.string(),
    theme: z.string().optional(),
    activeTeamId: z.nullable(z.string()),
    hasGithub: z.boolean().default(false),
    teams: z.array(TeamSummary$outboundSchema),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace User$ {
  /** @deprecated use `User$inboundSchema` instead. */
  export const inboundSchema = User$inboundSchema;
  /** @deprecated use `User$outboundSchema` instead. */
  export const outboundSchema = User$outboundSchema;
  /** @deprecated use `User$Outbound` instead. */
  export type Outbound = User$Outbound;
}

export function userToJSON(user: User): string {
  return JSON.stringify(User$outboundSchema.parse(user));
}

export function userFromJSON(
  jsonString: string,
): SafeParseResult<User, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => User$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'User' from JSON`,
  );
}
